{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.731.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Table\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "extendedProperties": [
      {
        "name": "TabularEditor_DeploymentMetadata",
        "type": "json",
        "value": {
          "ClientMachine": "DESKTOP-NV69I5J",
          "DeploymentMode": "SaveUI",
          "TabularEditorBuild": "3.9.0.2972",
          "Time": "2023-08-29T20:29:11.2364334+02:00",
          "User": "DESKTOP-NV69I5J\\Klonk-Temp"
        }
      }
    ],
    "relationships": [
      {
        "name": "afb3546c-43d8-48ac-aad4-ca45f6d7bf38",
        "fromColumn": "Month",
        "fromTable": "Table",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6428db5-956a-46cf-8e0d-f78eb01375b5",
            "sourceColumn": "Dimension",
            "summarizeBy": "none"
          },
          {
            "name": "SubDimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e30f180-4ec3-494a-b8ad-8c11697dd2f6",
            "sourceColumn": "SubDimension",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "90826514-1f5c-4f5a-97ec-cb24d73861b0",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "375a89cb-dd50-4436-8b44-7f963752da6a",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantitative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6707e5e6-d461-4e15-88ef-6d8c60a6e2a5",
            "sourceColumn": "Quantitative",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "74c7dcbc-f534-4da1-9c59-174298c17e81",
        "partitions": [
          {
            "name": "Table",
            "mode": "import",
            "source": {
              "expression": [
                "//let",
                "//    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs9PysnMK1bSUQrKTy9NBTEUFIwMjIyADCOlWB1kFeGZVYlFKXAlxkCGKZoSt8z0jJLUIhRjzNHU+ObnZaMYYgxW4F+UjN0ZFsjSWNxgaIisAJsLDFFswLAf4kDXnLJU7A4wNEVRgM0JRigqsLrBEkUJhiOglngk5qQBwykdu0uMMdRgcYwJhiKs7sFQheEkoKdiAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Dimension = _t, #\"Sub-Dimension\" = _t, Year = _t, Quantitative = _t]),",
                "//    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Quantitative\", Int64.Type}, {\"Year\", type text}})",
                "//in",
                "//    #\"Changed Type\"",
                "let",
                "    Dimensions = #table({\"Dimension\", \"SubDimension\"}, ",
                "                        {{\"Elves\", \"Fighter\"}, ",
                "                         {\"Elves\", \"Rogue\"}, ",
                "                         {\"Elves\", \"Sorcerer\"}, ",
                "                         {\"Goblins\", \"Fighter\"}, ",
                "                         {\"Goblins\", \"Rogue\"}, ",
                "                         {\"Goblins\", \"Sorcerer\"}, ",
                "                         {\"Orcs\", \"Fighter\"}, ",
                "                         {\"Orcs\", \"Rogue\"}, ",
                "                         {\"Orcs\", \"Sorcerer\"}}),",
                "                         ",
                "    DateList2022 = List.Dates(#date(2022, 1, 1), Duration.Days(#date(2022, 12, 31) - #date(2022, 1, 1)) + 1, #duration(1, 0, 0, 0)),",
                "    DateList2023 = List.Dates(#date(2023, 1, 1), Duration.Days(#date(2023, 9, 6) - #date(2023, 1, 1)) + 1, #duration(1, 0, 0, 0)),",
                "    CombinedDates = DateList2022 & DateList2023,",
                "    DateTable = Table.FromList(CombinedDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "",
                "    // Cross join dates and dimensions to create base table",
                "    JoinFunction = (DateValue) => Table.AddColumn(Dimensions, \"Month\", each DateValue),",
                "    CrossJoin = Table.TransformRows(DateTable, (row) => JoinFunction(row[Column1])),",
                "    MergedTable = Table.FromList(CrossJoin, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    FinalTableBase = Table.ExpandTableColumn(MergedTable, \"Column1\", {\"Dimension\", \"SubDimension\", \"Month\"}),",
                "",
                "    WithValues = Table.AddColumn(FinalTableBase, \"Quantitative\", each ",
                "        let ",
                "            YearValue = Date.Year([Month]),",
                "            RandomValue = Number.RoundDown(100 + Number.RandomBetween(-25, 25)),",
                "            BaseValue = 0 + RandomValue",
                "        in",
                "            if YearValue = 2022 then",
                "                BaseValue",
                "            else if YearValue = 2023 and [Dimension] <> \"Goblins\" then",
                "                BaseValue * 0.85",
                "            else if YearValue = 2023 and [Dimension] = \"Goblins\" then",
                "                BaseValue * 1.15",
                "            else ",
                "                0),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(WithValues,{{\"Quantitative\", Int64.Type}, {\"Month\", type date}, {\"SubDimension\", type text}, {\"Dimension\", type text}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Month]), Int64.Type)",
                "in",
                "    #\"Inserted Year\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "2. Report-Specific Objects",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "21661cfde1db4d40be113778b97a84f2"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05cd4f72-d741-444a-8849-796154a583d9",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "bc077534-c5b0-40dd-9fb4-4bad6abc2bd2",
        "measures": [
          {
            "name": "1 - Percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Stacked Percentages",
            "expression": "1 - [Percentage] ",
            "isHidden": true,
            "lineageTag": "a797f413-2545-4e12-a017-c9decafc3fa4"
          },
          {
            "name": "Zero",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Misc",
            "expression": "0",
            "formatString": "\" \"",
            "isHidden": true,
            "lineageTag": "9c5e001d-acf5-4a94-8c79-b36b22eddff2"
          },
          {
            "name": "90% of Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": "0.9 * [Sum]",
            "isHidden": true,
            "lineageTag": "3dfd2c42-1784-48db-b00d-f2279171b90d"
          },
          {
            "name": "Transparent",
            "displayFolder": "Control Colours",
            "expression": "\"#00000000\"",
            "isHidden": true,
            "lineageTag": "7af08448-2e99-4e55-a505-8e431865c8dd"
          },
          {
            "name": "One",
            "displayFolder": "Misc",
            "expression": "1",
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "ac584242-db7d-4988-837c-5bd76985c46d"
          },
          {
            "name": "5% of Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": "0.05 * [Sum]",
            "isHidden": true,
            "lineageTag": "7bf36b78-b7d5-408b-860f-e141b73f3749"
          },
          {
            "name": "110% of Highest Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.1 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "5b18d1b8-9148-45f3-8893-a6f86d294363"
          },
          {
            "name": "Min One",
            "displayFolder": "Misc",
            "expression": "-1",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebff2474-2af1-4c1e-b138-c5f3c295c261"
          },
          {
            "name": "120% of Highest Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "372933e1-0e0e-457e-8349-6aaaaa5cb5d9"
          },
          {
            "name": "Sum (2022; Inverse)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "For Format Strings",
            "expression": "- [Sum (2022)]",
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "2ad4db16-6991-4157-8219-d80f6deb39ed"
          },
          {
            "name": "2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "For Legends",
            "expression": "[Sum (2022; Inverse)]",
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "bec9c999-6fec-47de-8f1f-6e2ae0cd4437"
          },
          {
            "name": "2023",
            "displayFolder": "For Legends",
            "expression": "[Sum (2023)]",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8bcf8528-5a56-46a4-8577-7c5cfa488766"
          },
          {
            "name": "Year Colour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Colours",
            "expression": "IF ( SELECTEDVALUE ( 'Table'[Year] ) = \"  2022\", \"#ece6da\", \"#737068\" )",
            "isHidden": true,
            "lineageTag": "7a633807-acfb-4667-bf5f-0f51cfe82c98"
          },
          {
            "name": "Bar Chart & Candlestick - Change (Lower)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "IF ( ",
              "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
              "    MIN ( [Sum (2022)], [Sum (2023)] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "42be94b5-2cf7-403f-b817-e793d939313a"
          },
          {
            "name": "Bar Chart & Candlestick - Change (Higher)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "IF ( ",
              "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
              "    MAX ( [Sum (2022)], [Sum (2023)] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "06a8e96e-b86e-4795-ae87-d11205f3f7ee"
          },
          {
            "name": "Bar Chart & Candlestick - Bar Color",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )",
              "RETURN",
              "IF ( ",
              "    _Attribute = \"CHANGE\",",
              "    \"#00000000\",",
              "    IF (",
              "        _Attribute = \"2023\", \"#737068\",",
              "        \"#ece6da\"",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "2ac1fede-d563-4021-b19f-cb3ad7697b75"
          },
          {
            "name": "120% of Highest Sum by Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Year] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "72ea17f8-178e-48f7-a73d-2a0479fdd182"
          },
          {
            "name": "Bar Chart & Candlestick - Label Color",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )",
              "RETURN",
              "IF ( ",
              "    _Attribute = \"CHANGE\",",
              "    IF ( [Sum (Δ% '22 - '23)] > 0, \"#1f84bb\", \"#ec8b69\" ), \"#00000000\" )"
            ],
            "isHidden": true,
            "lineageTag": "0442ff64-b4ae-4dd0-bab9-992d9e1ec8f5"
          },
          {
            "name": "120% of Highest Delta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    MAX( [Sum (2022)], [Sum (2023)] ),",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        MAX( [Sum (2022)], [Sum (2023)] )",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e64df63d-9b51-4dea-b0c7-7cfd61781d41"
          },
          {
            "name": "Min 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Duplicated Measures for Formatting",
            "expression": "-2",
            "isHidden": true,
            "lineageTag": "8a4b18d3-f2cd-440b-a115-9c6339b8ae7a"
          },
          {
            "name": "Zero #3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Duplicated Measures for Formatting",
            "expression": "0",
            "isHidden": true,
            "lineageTag": "a4149ffb-966e-4875-a3a3-d540e6ece0e0"
          },
          {
            "name": "Goblins",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Goblins\", 0.75 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "159adc75-7072-42b0-93ca-599cd80e5992"
          },
          {
            "name": "Y-Axis (Progress III)",
            "displayFolder": "For Progress Bar III",
            "expression": [
              "",
              "VAR _Dimension = SELECTEDVALUE ( 'Table'[Dimension] ) ",
              "RETURN",
              "SWITCH(",
              "    _Dimension,",
              "    \"Halflings\", 0.95, ",
              "    \"Goblins\", 0.70,",
              "    \"Orcs\", 0.45,",
              "    \"Elves\", 0.20",
              "    ,0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3ae4415e-2da2-4c0a-9850-4dc0e09a9821"
          },
          {
            "name": "Yellow",
            "displayFolder": "For Progress Bar III",
            "expression": "0.25",
            "formatString": "0%;-0%;0%",
            "lineageTag": "7b2ecbaf-aa8b-439d-aeb4-dd5a256af54d"
          },
          {
            "name": "Orcs",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Goblins\", 0.5 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "c3bfd392-d6d1-4ed7-ba57-e90ec17dc9e8"
          },
          {
            "name": "Halflings",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Halflings\", 1 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "69d09b41-5a01-404b-b885-00bcb54f8111"
          },
          {
            "name": "Count (Format String)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTROWS( 'Table' )",
            "formatStringDefinition": {
              "expression": [
                "",
                "VAR _Count = [Count]",
                "VAR _Symbol =",
                "    SWITCH ( TRUE (),",
                "        _Count > 0, UNICHAR ( 10008 ),",
                "        _Count = 0, UNICHAR( 10004 ),",
                "        BLANK ()",
                "    )",
                "RETURN",
                "   \"#,##0 \" & _Symbol"
              ]
            },
            "lineageTag": "a823e998-d1ef-493c-a9a7-8e843dc61fc9"
          },
          {
            "name": "Waffle Subtitle",
            "displayFolder": "Waffle Chart (DAX Unicode)",
            "expression": [
              "",
              "VAR _Result = [Sum ('23 vs. '22)]",
              "RETURN",
              "\"Progress: \" & FORMAT ( _Result, \"#,##0%\" )"
            ],
            "lineageTag": "fb2bb51a-f88a-49e0-b70d-2c8f9bfe8a11"
          },
          {
            "name": "Color Indicator",
            "expression": [
              "",
              "VAR _Result = [Sum ('23 vs. '22)]",
              "VAR _Actuals = [Sum (2023)]",
              "VAR _Color = IF ( _Result < 1, UNICHAR ( 128308 ), UNICHAR ( 129482 ) )",
              "RETURN",
              "_Color & \" Actuals:\" & FORMAT ( _Actuals, \" #,##0\" )"
            ],
            "lineageTag": "65c9248a-39c8-491d-87ce-125866b90de7"
          },
          {
            "name": "Rating Subtitle",
            "displayFolder": "Rating (DAX Unicode)",
            "expression": [
              "",
              "VAR _Rating = [Sum ('23 vs. '22)] * 5",
              "RETURN",
              "\"Rating: \" & FORMAT ( _Rating, \"#,##0\" )"
            ],
            "lineageTag": "22a84017-ed7c-4e73-a82b-0982319caeab"
          },
          {
            "name": "Dumbbell Candle Lower (Green)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dumbbell Candlestick",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY > _PY, _PY )"
            ],
            "lineageTag": "efacd5f7-169e-4e7d-b4fd-746f35c92480"
          },
          {
            "name": "Dumbbell Candle Lower (Red)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dumbbell Candlestick",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY < _PY, _CY )"
            ],
            "lineageTag": "38f51b3a-e517-4ced-8582-2c1941fc8caf"
          },
          {
            "name": "Dumbbell Candle Upper (Green)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dumbbell Candlestick",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY > _PY, _CY )"
            ],
            "lineageTag": "ddabfcbe-403f-4e32-bb5c-9c775387f4fe"
          },
          {
            "name": "Dumbbell Candle Upper (Red)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dumbbell Candlestick",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY < _PY, _PY )"
            ],
            "lineageTag": "d636fe70-992e-4e3b-a007-3613a2b538a8"
          },
          {
            "name": "Waffle",
            "displayFolder": "Waffle Chart (DAX Unicode)",
            "expression": [
              "",
              "-- Init",
              "VAR _Actuals = [Sum (2023)]",
              "VAR _Target = [Sum (2022)]",
              "VAR _Perc = MIN(1, DIVIDE(_Actuals, _Target))  ",
              "VAR _TotalCells = 100",
              "VAR _RowLength = 10",
              "VAR _TotalRows = CEILING(DIVIDE(_TotalCells, _RowLength), 1)",
              "VAR _FilledCount = ROUND(_Perc * _TotalCells, 0) ",
              "",
              "-- Unicode characters",
              "VAR _Filled = UNICHAR(9632) & \" \" -- ■",
              "VAR _Empty = UNICHAR(9633) & \" \"  -- □",
              "",
              "-- Figure out the waffle Height x Width etc.",
              "VAR _FullFilledLines = INT(_FilledCount / _RowLength)",
              "VAR _FilledPartial = MOD(_FilledCount, _RowLength)",
              "VAR _EmptyPartial = _RowLength - _FilledPartial ",
              "VAR _FullEmptyLines = _TotalRows - _FullFilledLines - IF(_FilledPartial > 0, 1, 0)",
              "",
              "-- Result",
              "VAR _Waffle =",
              "    REPT(REPT(_Empty, _RowLength) & UNICHAR(10), _FullEmptyLines) &",
              "    IF(_FilledPartial > 0, REPT(_Filled, _FilledPartial) & REPT(_Empty, _EmptyPartial) & UNICHAR(10), \"\") &",
              "    REPT(REPT(_Filled, _RowLength) & UNICHAR(10), _FullFilledLines)",
              "RETURN",
              "    _Waffle",
              ""
            ],
            "lineageTag": "2ccd2bf1-9988-423e-abd0-12ccb403f7ae"
          },
          {
            "name": "Rating",
            "displayFolder": "Rating (DAX Unicode)",
            "expression": [
              "",
              "-- Init",
              "VAR _Actuals = [Sum (2023)] ",
              "VAR _Target = [Sum (2022)]  ",
              "VAR _Perc = MIN(1, DIVIDE(_Actuals, _Target))  ",
              "VAR _MaxStars = 5",
              "",
              "VAR _FilledStarsCount = INT(_Perc * _MaxStars)",
              "VAR _HalfStar = IF(MOD(_Perc * _MaxStars, 1) >= 0.5, 1, 0)",
              "VAR _EmptyStarsCount = _MaxStars - _FilledStarsCount - _HalfStar",
              "",
              "",
              "-- Unicode characters",
              "VAR _FilledStar = UNICHAR(9733)         -- ★",
              "VAR _HalfFilledStar = UNICHAR(10030)    -- ✮",
              "VAR _EmptyStar = UNICHAR(9734)          -- ☆",
              "",
              "",
              "-- Result",
              "VAR _StarRating =",
              "    REPT(_FilledStar, _FilledStarsCount) &",
              "    REPT(_HalfFilledStar, _HalfStar) &",
              "    REPT(_EmptyStar, _EmptyStarsCount)",
              "",
              "RETURN",
              "    _StarRating & UNICHAR (10)",
              ""
            ],
            "lineageTag": "860209d7-5ea2-4a48-9ea1-2f9e7df39fce"
          },
          {
            "name": "Context Subtitle",
            "expression": [
              "",
              "VAR _Perc = [Sum (Δ% '22 - '23)]",
              "VAR _Color = \"   ( \" & IF ( _Perc < 1, UNICHAR ( 9660 ), UNICHAR ( 9650 ) )",
              "VAR _Target = [Sum (2022)]",
              "RETURN",
              "\"1 Year Prior: \" & FORMAT ( _Target, \"#,##0\" ) & _Color & FORMAT ( _Perc, \" #,##0.0%; #,##0.0%; #,##0%\" ) & \" )\""
            ],
            "lineageTag": "faf3bed7-a8d6-42b2-b0e4-edc35cd41bed"
          }
        ],
        "partitions": [
          {
            "name": "2. Report-Specific Objects",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "1. Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "724d8a875a79418db6f9113a2cf5d8eb"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18e219e8-e8e5-4a4e-8c86-825ff8a663c7",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4bd4c7d3-ed8c-4fc9-802b-4eb3b0893f5d",
        "measures": [
          {
            "name": "Percentage",
            "expression": [
              "",
              "VAR _Total = CALCULATE( SUM ( 'Table'[Quantitative] ), REMOVEFILTERS ( ) )",
              "RETURN",
              "DIVIDE ( ",
              "    SUM ( 'Table'[Quantitative] ), ",
              "    _Total",
              ") + 0.15"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ccbbf42b-88e3-4b49-8192-f592b6d02dc4"
          },
          {
            "name": "Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "expression": "SUM ( 'Table'[Quantitative] )",
            "formatString": "  #,##0",
            "lineageTag": "71445de7-2cd6-43b8-81cb-8b9dd1159740"
          },
          {
            "name": "Sum (2023)",
            "expression": [
              "",
              "// This would normally be just the sum; where Sum (2022) would be using time intelligence or a similar method to calculate PY",
              "CALCULATE(",
              "    [Sum],",
              "    DATESYTD('Table'[Month])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "202a6bc8-71c3-41cc-9349-cde551b031a0"
          },
          {
            "name": "Sum (2022)",
            "expression": [
              "",
              "// This would normally be calculated using time intelligence or a similar method to calculate PY",
              "CALCULATE(",
              "    [Sum (2023)],",
              "    SAMEPERIODLASTYEAR('Table'[Month])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6fe52e9a-2944-457b-97e7-ee4aadcdc2cc"
          },
          {
            "name": "Sum (Δ '22 - '23)",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "VAR _Delta = _CY - _PY",
              "RETURN",
              "_Delta"
            ],
            "formatString": "0",
            "lineageTag": "4cb18752-6c6d-444e-b2dd-dff2e86ce817"
          },
          {
            "name": "Sum (Δ% '22 - '23)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Sum (Δ '22 - '23)],",
              "    [Sum (2022)]",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "",
                "VAR _UpArrow = UNICHAR(8595)",
                "VAR _DownArrow = UNICHAR(8593)",
                "RETURN",
                "   _DownArrow & \" #,##0.0%\" & \";\" &    // Negative numbers",
                "   _UpArrow & \" #,##0.0%\" & \";\" &      // Positive numbers",
                "   \"#,##0.0\"                           // Zero"
              ]
            },
            "lineageTag": "546753a4-f8e4-45be-92c8-3a0ccdc60f66"
          },
          {
            "name": "Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTROWS( VALUES('Table'[Dimension]) )",
            "lineageTag": "4b4de92d-e3ee-4139-a985-1b450ff40060"
          },
          {
            "name": "Sum ('23 vs. '22)",
            "expression": [
              "",
              "VAR _Actuals = [Sum (2023)]",
              "VAR _Target = [Sum (2022)]",
              "VAR _Perc = DIVIDE(_Actuals, _Target)",
              "RETURN",
              "    _Perc"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "efdaa006-24a4-4a68-a810-343bf07e07ee"
          },
          {
            "name": "Rolling 2-Week Sum",
            "expression": [
              "",
              "VAR _RollingSum = ",
              "    CALCULATE(",
              "        [Sum],",
              "        DATESINPERIOD(",
              "            'Date'[Date],",
              "            LASTDATE('Date'[Date]),",
              "            -14,",
              "            DAY",
              "        )",
              "    )",
              "VAR _MaxDateTable = MAX ( 'Date'[Date] )",
              "VAR _MaxDate = MAX ( 'Table'[Month] )",
              "VAR _Result = ",
              "    IF (_MaxDateTable > _MaxDate, _RollingSum )",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "2a3d3b47-00b8-44e3-9f64-d00a9b2f77bb"
          }
        ],
        "partitions": [
          {
            "name": "1. Measures",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "3. Report-Specific Calculation Group",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "2023",
              "expression": "[Sum (2023)]",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING ()"
              },
              "ordinal": 1
            },
            {
              "name": "2022",
              "expression": "[Sum (2022)]",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING ()"
              },
              "ordinal": 0
            },
            {
              "name": "CHANGE",
              "expression": [
                "",
                "MAX ( [Sum (2022)], [Sum (2023)] )",
                ""
              ],
              "formatStringDefinition": {
                "expression": "[Sum (Δ% '22 - '23)]"
              },
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "46153ef3-7f1e-4409-9fd9-da8badcc1c16",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "eb4d2363-14da-44a2-b9e8-6a6b70069eea",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "e8e227b7-fd27-4a64-87a2-95da79648028",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "3. Report-Specific Disconnected Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "803854adc3014b728952e70307c7162a"
          }
        ],
        "columns": [
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b683d841-5ca8-40dc-a3aa-b94c9aa78716",
            "sortByColumn": "Order",
            "sourceColumn": "[Attribute]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "781445e6-72e9-47cf-ae90-7148209c7c40",
            "sourceColumn": "[Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "fe2cdcff-7270-464b-bddc-7b06cdc7fdc3",
        "measures": [
          {
            "name": "Bar Chart & Candlestick",
            "expression": [
              "",
              "// sqlbi measure replacement method",
              "CALCULATE( ",
              "    [Zero],",
              "    TREATAS(",
              "        DISTINCT( '3. Report-Specific Disconnected Table'[Attribute] ),",
              "        '3. Report-Specific Calculation Group'[Attribute]",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "IF ( ",
                "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
                "    FORMAT( [Sum (Δ% '22 - '23)], \"+0\\.0%;-0\\.0%;0\\.0%\"),",
                "    \"#,##0\"",
                ")"
              ]
            },
            "isHidden": true,
            "lineageTag": "0e596993-63a5-42a9-9dc0-aa320666263d"
          }
        ],
        "partitions": [
          {
            "name": "3. Report-Specific Disconnected Table",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SELECTCOLUMNS( ",
                "    '3. Report-Specific Calculation Group',",
                "    \"Attribute\", '3. Report-Specific Calculation Group'[Attribute],",
                "    \"Order\", '3. Report-Specific Calculation Group'[Ordinal] ",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "163d92fff6ed49ff9051b07d98c0444d"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "79acd4a7-177f-46ac-b3f5-bd96e78c9259",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "72d1b233-6932-4389-8501-3541eeaff684",
            "sourceColumn": "[Month Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "42924f7d-1875-49e1-abad-09dccdadd421",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    ADDCOLUMNS(",
                "        CALENDAR( DATE(2022, 1, 1), DATE(2023, 12, 31) ),",
                "        \"Month Year\", FORMAT( [Date], \"MMYYYY\" )",
                "    )    "
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}