{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.731.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Table\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "extendedProperties": [
      {
        "name": "TabularEditor_DeploymentMetadata",
        "type": "json",
        "value": {
          "ClientMachine": "DESKTOP-NV69I5J",
          "DeploymentMode": "SaveUI",
          "TabularEditorBuild": "3.9.0.2972",
          "Time": "2023-07-26T01:35:00.5333614+02:00",
          "User": "DESKTOP-NV69I5J\\Klonk-Temp"
        }
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6428db5-956a-46cf-8e0d-f78eb01375b5",
            "sourceColumn": "Dimension",
            "summarizeBy": "none"
          },
          {
            "name": "Quantitative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea479855-4c8e-45af-927c-60b87abbeb86",
            "sourceColumn": "Quantitative",
            "summarizeBy": "sum"
          },
          {
            "name": "Sub-Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f44d7b1-03be-4dc8-ad1c-32b4503fb996",
            "sourceColumn": "Sub-Dimension",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f94a7412-424a-4c12-9e19-6a928be50131",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "74c7dcbc-f534-4da1-9c59-174298c17e81",
        "partitions": [
          {
            "name": "Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs9PysnMK1bSUQrKTy9NBTEUFIwMjIyADCOlWB1kFeGZVYlFKXAlxkCGKZoSt8z0jJLUIhRjzNHU+ObnZaMYYgxW4F+UjN0ZFsjSWNxgaIisAJsLDFFswLAf4kDXnLJU7A4wNEVRgM0JRigqsLrBEkUJhiOglngk5qQBwykdu0uMMdRgcYwJhiKs7sFQheEkoKdiAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Dimension = _t, #\"Sub-Dimension\" = _t, Year = _t, Quantitative = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Quantitative\", Int64.Type}, {\"Year\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "2. Report-Specific Objects",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "21661cfde1db4d40be113778b97a84f2"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05cd4f72-d741-444a-8849-796154a583d9",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "bc077534-c5b0-40dd-9fb4-4bad6abc2bd2",
        "measures": [
          {
            "name": "1 - Percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Stacked Percentages",
            "expression": "1 - [Percentage] ",
            "isHidden": true,
            "lineageTag": "a797f413-2545-4e12-a017-c9decafc3fa4"
          },
          {
            "name": "Zero",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Misc",
            "expression": "0",
            "formatString": "\" \"",
            "isHidden": true,
            "lineageTag": "9c5e001d-acf5-4a94-8c79-b36b22eddff2"
          },
          {
            "name": "90% of Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": "0.9 * [Sum]",
            "isHidden": true,
            "lineageTag": "3dfd2c42-1784-48db-b00d-f2279171b90d"
          },
          {
            "name": "Transparent",
            "displayFolder": "Control Colours",
            "expression": "\"#00000000\"",
            "isHidden": true,
            "lineageTag": "7af08448-2e99-4e55-a505-8e431865c8dd"
          },
          {
            "name": "One",
            "displayFolder": "Misc",
            "expression": "1",
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "ac584242-db7d-4988-837c-5bd76985c46d"
          },
          {
            "name": "5% of Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": "0.05 * [Sum]",
            "isHidden": true,
            "lineageTag": "7bf36b78-b7d5-408b-860f-e141b73f3749"
          },
          {
            "name": "110% of Highest Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.1 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "5b18d1b8-9148-45f3-8893-a6f86d294363"
          },
          {
            "name": "Min One",
            "displayFolder": "Misc",
            "expression": "-1",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebff2474-2af1-4c1e-b138-c5f3c295c261"
          },
          {
            "name": "120% of Highest Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "372933e1-0e0e-457e-8349-6aaaaa5cb5d9"
          },
          {
            "name": "Sum (2022; Inverse)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "For Format Strings",
            "expression": "- [Sum (2022)]",
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "2ad4db16-6991-4157-8219-d80f6deb39ed"
          },
          {
            "name": "2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "For Legends",
            "expression": "[Sum (2022; Inverse)]",
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "bec9c999-6fec-47de-8f1f-6e2ae0cd4437"
          },
          {
            "name": "2023",
            "displayFolder": "For Legends",
            "expression": "[Sum (2023)]",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8bcf8528-5a56-46a4-8577-7c5cfa488766"
          },
          {
            "name": "Year Colour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Colours",
            "expression": "IF ( SELECTEDVALUE ( 'Table'[Year] ) = \"  2022\", \"#ece6da\", \"#737068\" )",
            "isHidden": true,
            "lineageTag": "7a633807-acfb-4667-bf5f-0f51cfe82c98"
          },
          {
            "name": "Bar Chart & Candlestick - Change (Lower)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "IF ( ",
              "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
              "    MIN ( [Sum (2022)], [Sum (2023)] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "42be94b5-2cf7-403f-b817-e793d939313a"
          },
          {
            "name": "Bar Chart & Candlestick - Change (Higher)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "IF ( ",
              "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
              "    MAX ( [Sum (2022)], [Sum (2023)] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "06a8e96e-b86e-4795-ae87-d11205f3f7ee"
          },
          {
            "name": "Bar Chart & Candlestick - Bar Color",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )",
              "RETURN",
              "IF ( ",
              "    _Attribute = \"CHANGE\",",
              "    \"#00000000\",",
              "    IF (",
              "        _Attribute = \"2023\", \"#737068\",",
              "        \"#ece6da\"",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "2ac1fede-d563-4021-b19f-cb3ad7697b75"
          },
          {
            "name": "120% of Highest Sum by Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Year] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "72ea17f8-178e-48f7-a73d-2a0479fdd182"
          },
          {
            "name": "Bar Chart & Candlestick - Label Color",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )",
              "RETURN",
              "IF ( ",
              "    _Attribute = \"CHANGE\",",
              "    IF ( [Sum (Δ% '22 - '23)] > 0, \"#1f84bb\", \"#ec8b69\" ), \"#00000000\" )"
            ],
            "isHidden": true,
            "lineageTag": "0442ff64-b4ae-4dd0-bab9-992d9e1ec8f5"
          },
          {
            "name": "120% of Highest Delta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    MAX( [Sum (2022)], [Sum (2023)] ),",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        MAX( [Sum (2022)], [Sum (2023)] )",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e64df63d-9b51-4dea-b0c7-7cfd61781d41"
          },
          {
            "name": "Min 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Duplicated Measures for Formatting",
            "expression": "-2",
            "isHidden": true,
            "lineageTag": "8a4b18d3-f2cd-440b-a115-9c6339b8ae7a"
          },
          {
            "name": "Zero #3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Duplicated Measures for Formatting",
            "expression": "0",
            "isHidden": true,
            "lineageTag": "a4149ffb-966e-4875-a3a3-d540e6ece0e0"
          },
          {
            "name": "Goblins",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Goblins\", 0.75 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "159adc75-7072-42b0-93ca-599cd80e5992"
          },
          {
            "name": "Y-Axis (Progress III)",
            "displayFolder": "For Progress Bar III",
            "expression": [
              "",
              "VAR _Dimension = SELECTEDVALUE ( 'Table'[Dimension] ) ",
              "RETURN",
              "SWITCH(",
              "    _Dimension,",
              "    \"Halflings\", 0.95, ",
              "    \"Goblins\", 0.70,",
              "    \"Orcs\", 0.45,",
              "    \"Elves\", 0.20",
              "    ,0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3ae4415e-2da2-4c0a-9850-4dc0e09a9821"
          },
          {
            "name": "Yellow",
            "displayFolder": "For Progress Bar III",
            "expression": "0.25",
            "formatString": "0%;-0%;0%",
            "lineageTag": "7b2ecbaf-aa8b-439d-aeb4-dd5a256af54d"
          },
          {
            "name": "Orcs",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Goblins\", 0.5 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "c3bfd392-d6d1-4ed7-ba57-e90ec17dc9e8"
          },
          {
            "name": "Halflings",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Halflings\", 1 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "69d09b41-5a01-404b-b885-00bcb54f8111"
          }
        ],
        "partitions": [
          {
            "name": "2. Report-Specific Objects",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "1. Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "724d8a875a79418db6f9113a2cf5d8eb"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18e219e8-e8e5-4a4e-8c86-825ff8a663c7",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4bd4c7d3-ed8c-4fc9-802b-4eb3b0893f5d",
        "measures": [
          {
            "name": "Percentage",
            "expression": [
              "",
              "VAR _Total = CALCULATE( SUM ( 'Table'[Quantitative] ), REMOVEFILTERS ( ) )",
              "RETURN",
              "DIVIDE ( ",
              "    SUM ( 'Table'[Quantitative] ), ",
              "    _Total",
              ") + 0.15"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ccbbf42b-88e3-4b49-8192-f592b6d02dc4"
          },
          {
            "name": "Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "expression": "SUM ( 'Table'[Quantitative] )",
            "formatString": "  #,##0",
            "lineageTag": "71445de7-2cd6-43b8-81cb-8b9dd1159740"
          },
          {
            "name": "Sum (2023)",
            "expression": [
              "",
              "// This would normally be just the sum; where Sum (2022) would be using time intelligence or a similar method to calculate PY",
              "CALCULATE(",
              "    [Sum],",
              "    'Table'[Year] = \"  2023\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "202a6bc8-71c3-41cc-9349-cde551b031a0"
          },
          {
            "name": "Sum (2022)",
            "expression": [
              "",
              "// This would normally be calculated using time intelligence or a similar method to calculate PY",
              "CALCULATE(",
              "    [Sum],",
              "    'Table'[Year] = \"  2022\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6fe52e9a-2944-457b-97e7-ee4aadcdc2cc"
          },
          {
            "name": "Sum (Δ '22 - '23)",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "VAR _Delta = _CY - _PY",
              "RETURN",
              "_Delta"
            ],
            "formatString": "0",
            "lineageTag": "4cb18752-6c6d-444e-b2dd-dff2e86ce817"
          },
          {
            "name": "Sum (Δ% '22 - '23)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Sum (Δ '22 - '23)],",
              "    [Sum (2022)]",
              ")"
            ],
            "formatString": "+#,##0.0%;-#,##0.0%;#,##0.0%",
            "lineageTag": "546753a4-f8e4-45be-92c8-3a0ccdc60f66"
          },
          {
            "name": "Dumbbell Candle Upper (Green)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY > _PY, _CY )"
            ],
            "lineageTag": "ddabfcbe-403f-4e32-bb5c-9c775387f4fe"
          },
          {
            "name": "Dumbbell Candle Lower (Green)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY > _PY, _PY )"
            ],
            "lineageTag": "efacd5f7-169e-4e7d-b4fd-746f35c92480"
          },
          {
            "name": "Dumbbell Candle Upper (Red)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY < _PY, _PY )"
            ],
            "lineageTag": "d636fe70-992e-4e3b-a007-3613a2b538a8"
          },
          {
            "name": "Dumbbell Candle Lower (Red)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY < _PY, _CY )"
            ],
            "lineageTag": "38f51b3a-e517-4ced-8582-2c1941fc8caf"
          },
          {
            "name": "Average",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE( 'Table'[Quantitative] )",
            "lineageTag": "9e1730ae-9fa7-4e42-ab67-b1258eff1fa6"
          }
        ],
        "partitions": [
          {
            "name": "1. Measures",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "3. Report-Specific Calculation Group",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "2023",
              "expression": "[Sum (2023)]",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING ()"
              },
              "ordinal": 1
            },
            {
              "name": "2022",
              "expression": "[Sum (2022)]",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING ()"
              },
              "ordinal": 0
            },
            {
              "name": "CHANGE",
              "expression": [
                "",
                "MAX ( [Sum (2022)], [Sum (2023)] )",
                ""
              ],
              "formatStringDefinition": {
                "expression": "[Sum (Δ% '22 - '23)]"
              },
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "46153ef3-7f1e-4409-9fd9-da8badcc1c16",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "eb4d2363-14da-44a2-b9e8-6a6b70069eea",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "e8e227b7-fd27-4a64-87a2-95da79648028",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "3. Report-Specific Disconnected Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "803854adc3014b728952e70307c7162a"
          }
        ],
        "columns": [
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b683d841-5ca8-40dc-a3aa-b94c9aa78716",
            "sortByColumn": "Order",
            "sourceColumn": "[Attribute]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "781445e6-72e9-47cf-ae90-7148209c7c40",
            "sourceColumn": "[Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "fe2cdcff-7270-464b-bddc-7b06cdc7fdc3",
        "measures": [
          {
            "name": "Bar Chart & Candlestick",
            "expression": [
              "",
              "// sqlbi measure replacement method",
              "CALCULATE( ",
              "    [Zero],",
              "    TREATAS(",
              "        DISTINCT( '3. Report-Specific Disconnected Table'[Attribute] ),",
              "        '3. Report-Specific Calculation Group'[Attribute]",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "IF ( \r",
                "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",\r",
                "    FORMAT( [Sum (Δ% '22 - '23)], \"+0\\.0%;-0\\.0%;0\\.0%\"),\r",
                "    \"#,##0\"\r",
                ")"
              ]
            },
            "isHidden": true,
            "lineageTag": "0e596993-63a5-42a9-9dc0-aa320666263d"
          }
        ],
        "partitions": [
          {
            "name": "3. Report-Specific Disconnected Table",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SELECTCOLUMNS( ",
                "    '3. Report-Specific Calculation Group',",
                "    \"Attribute\", '3. Report-Specific Calculation Group'[Attribute],",
                "    \"Order\", '3. Report-Specific Calculation Group'[Ordinal] ",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "4. Report-Specific SVG Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4f5be44a59594685aa453dcbf609e978"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ea94bcb1-fc74-4dcb-bb99-815fc2be8ccb",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f4ab3a84-bd81-4db3-82e0-074ee7960e80",
        "measures": [
          {
            "name": "Card with Columns and Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "/* SETUP */",
              "VAR _spaceBetweenColumns = 5.5 // Space that will be reserved between columns",
              "VAR _maxSizeOfColumn = 3.5 // Max size of column, if the calculated value is bigger than this, the column will be this size",
              "VAR _columnRounding = 5 // Rounding of column corners",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 250 // Height size of the SVG",
              "VAR _initialTbl = // ADD YOUR TABLE, PERIOD COLUMN (DATE, MONTH, QUARTER, YEAR,...) + MEASURE HERE",
              "    ADDCOLUMNS (",
              "        SELECTCOLUMNS(SUMMARIZE ( 'Table', 'Table'[Quantitative] ), \"@xAxisPeriod\", [Quantitative] ),",
              "        \"@val\", [Sum]",
              "    )",
              "VAR _target = [Average] // Target value or measure",
              "",
              "/* TEXT DECLARTIONS */",
              "VAR _firstLineInitialText = \"Total target is on\"",
              "VAR _firstLineEndText =  \"~ missing\"",
              "VAR _secondLineInitialText = \"Period target is on\"",
              "VAR _secondLineEndText =  \"~ sold\"",
              "VAR _thirdLineMiddleText = \"of\"",
              "VAR _thirdLineEndText =  \"months were successful\"",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _grey = \"#E6E6E6\" // Will be used for all other columns",
              "VAR _activePartsColor = \"#658E95\" // Will be used for all highly colored parts of card",
              "VAR _darkGrey = \"#808080\" // Will be used for all text",
              "VAR _targetLineColor = \"#A8A8A8\" // Will be used for target line",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' width='\"&_width&\"' height='\"&_height&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CSS DECLARATIONS */",
              "VAR _style = ",
              "\"<style>",
              "    text{",
              "        font-family:Segoe UI;",
              "    }",
              "    .columns{",
              "         opacity: 1;",
              "         outline: none;",
              "    }",
              "    .line{",
              "        stroke:\"&_targetLineColor&\"; ",
              "        stroke-width:1.25;",
              "        stroke-dasharray:5 5;",
              "    }",
              "    .txtGroup{",
              "        dominant-baseline: middle;",
              "        text-anchor:start;",
              "    }",
              "    .bolder{",
              "        font-weight: bold;",
              "    }",
              "</style>\"",
              "",
              "/* CALCULATION */",
              "VAR _preparedTbl = ",
              "    ADDCOLUMNS (",
              "        _initialTbl,",
              "        \"@rowNum\", ROWNUMBER (_initialTbl, ORDERBY ( [@xAxisPeriod], ASC ) )",
              "    )",
              "VAR _maxValue =",
              "    MAXX ( _preparedTbl, [@val] )",
              "VAR _rowCounter =",
              "    COUNTROWS ( _preparedTbl )",
              "VAR _modifiedValue = _rowCounter*_target",
              "VAR _resultSizeOfColumns =",
              "    VAR _cal =",
              "        ROUND ( DIVIDE ( 100 - ( ( _rowCounter + 1 ) * _spaceBetweenColumns ), _rowCounter ), 1 )",
              "    RETURN",
              "        IF ( _cal > _maxSizeOfColumn, _maxSizeOfColumn, _cal )",
              "VAR _columns =",
              "    CONCATENATEX (",
              "        _preparedTbl,",
              "        VAR _colorOfColumn =",
              "            IF(_target<[@val],_activePartsColor,_grey) // Rules for coloring columns",
              "        VAR _startOfColumn =",
              "            ROUND ( DIVIDE ( [@val], _maxValue ) * 40, 1 )",
              "        VAR _positionCounter = ( ( [@rowNum] - 1 ) * _resultSizeOfColumns ) + ( _spaceBetweenColumns * [@rowNum] )",
              "        RETURN",
              "            \"<rect class='columns' x='\" & _positionCounter & \"%' y='\" & 85-_startOfColumn & \"%' width='\" & _resultSizeOfColumns & \"%' height='\" & _startOfColumn & \"%' fill='\" & _colorOfColumn & \"' rx='\"&_columnRounding&\"' />\"",
              "    )",
              "VAR _targetLine =",
              "    VAR _y = 85-ROUND ( DIVIDE ( _target, _maxValue ) * 40, 1 )",
              "    RETURN",
              "    \"<line class='line' x1='\"&_spaceBetweenColumns&\"%' x2='\"&100-_spaceBetweenColumns&\"%' y1='\"&_y&\"%' y2='\"&_y&\"%' />\"",
              "VAR _initialText =",
              "\"<g class='txtGroup'>\"&",
              "    \"<text y='4%' x='2.5%' font-size='107.5%' fill='\"&_darkGrey&\"'><tspan class='bolder'> \"&_firstLineInitialText&\" <tspan fill='\"&_activePartsColor&\"'>\"",
              "        &FORMAT(ROUND(DIVIDE(SUMX(_preparedTbl,[@val]),_modifiedValue),2),\"0%\")& ",
              "        \"</tspan></tspan><tspan font-size='80%'> \"&_firstLineEndText&\" \"&_modifiedValue-SUMX(_preparedTbl,[@val])&\" </tspan>",
              "    </text>\"",
              "    &",
              "    \"<text y='16.5%' x='2.5%' fill='\"&_darkGrey&\"'>",
              "        \"&_secondLineInitialText&\" <tspan fill='\"&_activePartsColor&\"' class='bolder'>\"",
              "        &FORMAT(ROUND(DIVIDE(SUMX(_preparedTbl,[@val]),_modifiedValue),2),\"0%\")& ",
              "        \"</tspan> <tspan font-size='80%'> \"&_secondLineEndText&\" \"&SUMX(_preparedTbl,[@val])&\" </tspan>",
              "    </text>\"",
              "    &",
              "    \"<text y='29%' x='2.5%' fill='\"&_darkGrey&\"'>",
              "        <tspan fill='\"&_activePartsColor&\"' class='bolder'>\"",
              "        & COUNTROWS(FILTER(_preparedTbl,[@val]>=_target)) & ",
              "        \"</tspan> \"&_thirdLineMiddleText&\"",
              "        <tspan class='bolder'>\"",
              "        & _rowCounter & ",
              "        \"</tspan> \"&_thirdLineEndText&\"",
              "    </text>",
              "</g>\"",
              "VAR SVGImageURL = _svgDeclaration & _svgHeader & _style & _initialText & _targetLine &  _columns  & _svgEnd",
              "RETURN",
              "    SVGImageURL"
            ],
            "lineageTag": "6a23f99d-c620-4dff-8827-4e4ba637002a"
          },
          {
            "name": "Card with Donut progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "/* SETUP */",
              "VAR _total = [Sum (2022)]  // Will be used as a target",
              "VAR _value = [Sum (2023)] // Will be used as a current value",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "VAR _CanvasSize = MIN(_height,_width) // Canvas size",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "",
              "/* PRE CALCULATION */",
              "VAR _halfSize = _CanvasSize/2 // Half of the canvas size",
              "VAR _r = _halfSize-_paddning*1.5 // Radius of the circle",
              "VAR _round = 2*PI()*_r",
              "VAR _perc = _value/_total // Percentage of the current value",
              "VAR _ratio = _round-_round*_perc // Ratio of the current value",
              "VAR _clr =  // Determine the color of the circle based on the percentage",
              "    SWITCH(TRUE(),",
              "        _perc>=0.75,_positive, // Positive Color",
              "        _perc>=0.5,_neutral, // Neutral Color",
              "        _negative // Negative Color",
              "    )",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _styles = ",
              "\"",
              "  <style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              "    .backgroundCircle{",
              "      transform:rotate(-90deg) translate(-\"&(_height+_width)/2&\"px, \"&(_width-_height)/2&\"px);",
              "    }",
              "    .backgroundCircle{",
              "      fill: transparent;",
              "      stroke-width: \"&_paddning&\";",
              "    }",
              "    .background{",
              "      stroke: #e0e0e0;",
              "    }",
              "    .filling{",
              "      stroke: \"&_clr&\";",
              "      stroke-linecap: round;",
              "      stroke-dasharray: \"&_round&\";",
              "      stroke-dashoffset: \"&_ratio&\";",
              "    }",
              "    .mainText{",
              "      fill: \"&_clr&\";",
              "      font-size: 225%;",
              "      text-anchor: middle;",
              "      dominant-baseline: middle;",
              "      font-weight: bold;",
              "    }",
              "    .subTexts{",
              "      fill: #CCCCCC;",
              "      font-size: 95%;",
              "      dominant-baseline: middle;",
              "    }",
              "    .leftPositioned{",
              "        text-anchor: end;",
              "    }",
              "    .rightPositioned{",
              "        text-anchor: start;",
              "    }",
              "    .bolden{",
              "        font-weight: bold;",
              "    }",
              "  </style>",
              "\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _sv =",
              "\"",
              "  <g class='backgroundCircle'>",
              "  <circle r='\"&_r&\"' cx='50%' cy='50%' class='background' />",
              "  <circle r='\"&_r&\"' cx='50%' cy='50%' class='filling'/>",
              "  </g>",
              "  <g class='mainText'>",
              "  <text x='50%' y='37.5%' >\"&FORMAT(_perc,\"0.0%\")&\"</text>",
              "  </g>",
              "  <g class='subTexts'>",
              "  <g class='leftPositioned'>",
              "  <text x='51%' y='50.5%' >\"&\"Target:\"&\"</text>",
              "  <text x='51%' y='60%' >\"&\"Current:\"&\"</text>",
              "  <text x='51%' y='69.5%' class='bolden'>\"&\"Missing:\"&\"</text>",
              "  </g>",
              "  <g class='rightPositioned'>",
              "  <text x='53%' y='50.5%' >\"&_total&\"</text>",
              "  <text x='53%' y='60%' >\"&ROUND(_value,1)&\"</text>",
              "  <text x='53%' y='69.5%' class='bolden'>\"&ROUND(_total-_value,1)&\"</text>",
              "  </g>",
              "  </g>",
              "\"",
              "VAR _result = _svgDeclaration & _svgHeader & _styles & _sv & _svgEnd ",
              "RETURN",
              "   _result"
            ],
            "lineageTag": "9f7ba69f-7cec-4a41-a562-10e51f9ac0a2"
          },
          {
            "name": "Text Card ShowCase One",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _actualQuantity = [Sum (2023)] // Get the actual quantity from the context (Usually it would be measure for the actual year)",
              "VAR _previousQuantity = [Sum (2022)] // Get the previous quantity from the context (Usually it would be measure for the previous year)",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _grey = \"#BBB\"",
              "VAR _bolderGrey = \"#808080\"",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    font-size:85%;",
              "    fill:\"&_grey&\";",
              "}",
              ".bolder{",
              "    font-weight:bold;",
              "    fill:\"&_bolderGrey&\";",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _div = DIVIDE(_actualQuantity,_previousQuantity)-1",
              "VAR _colorForPercentage = ",
              "    SWITCH(TRUE(),",
              "        _div>0,_positive,",
              "        _div<0,_negative,",
              "        _neutral",
              "    )",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText'>",
              "        <text y='10%'>",
              "            In year \"&_yearDefinition&\" were <tspan class='bolder'>\"& _actualQuantity &\"</tspan> members of individual races.",
              "        </text>",
              "        <text y='22.5%'>",
              "            It is about <tspan class='bolder'>\"& FORMAT(_actualQuantity-_previousQuantity,\"+# more;-# less\") &\" <tspan font-size='85%' fill='\"&_colorForPercentage&\"'>( \"&FORMAT(_div,\"+0.0%;-0.0%\")&\")</tspan></tspan> then previous year.",
              "        </text>",
              "    </g>\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _content & _svgEnding"
            ],
            "lineageTag": "c2f6787a-34a5-42fc-99a8-da203f868e63"
          },
          {
            "name": "Text Card ShowCase Two",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _tableInitiator =",
              "CALCULATETABLE(",
              "    ADDCOLUMNS(",
              "        VALUES('Table'[Dimension]),",
              "        \"@counter\", [Sum]",
              "    ),",
              "    KEEPFILTERS('Table'[Year] = _yearDefinition)",
              ")",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    font-size:85%;",
              "    fill:#BBB;",
              "}",
              ".bolder{",
              "    font-weight:bold;",
              "    fill:#808080;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _counter = COUNTROWS(_tableInitiator)",
              "VAR _topRow = INDEX(1,_tableInitiator,ORDERBY([@counter],DESC))",
              "VAR _topRace = SELECTCOLUMNS(_topRow,[Dimension])",
              "VAR _topRaceMembers = SELECTCOLUMNS(_topRow,[@counter])",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText'>",
              "        <text y='10%'>",
              "            In evidence are <tspan class='bolder'>\"& _counter &\"</tspan> races.",
              "        </text>",
              "        <text y='22.5%'>",
              "            Largest race currently are <tspan class='bolder'>\"& _topRace &\"</tspan> with <tspan class='bolder'>\"&_topRaceMembers&\"</tspan> members.",
              "        </text>",
              "    </g>\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _content & _svgEnding"
            ],
            "lineageTag": "f1b5120b-0bad-4f65-9a59-49b37d2d3a28"
          },
          {
            "name": "Text Card ShowCase Three",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _tableInitiator =",
              "CALCULATETABLE(",
              "    ADDCOLUMNS(",
              "        VALUES('Table'[Sub-Dimension]),",
              "        \"@counter\", [Sum]",
              "    ),",
              "    KEEPFILTERS('Table'[Year] = _yearDefinition && 'Table'[Dimension] = \"Elves\")",
              ")",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    font-size:85%;",
              "    fill:#BBB;",
              "}",
              ".bolder{",
              "    font-weight:bold;",
              "    fill:#808080;",
              "}",
              ".smallerItalic{",
              "    font-size:85%;",
              "    font-style: italic;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _counter = COUNTROWS(_tableInitiator)",
              "VAR _topRow = INDEX(1,_tableInitiator,ORDERBY([@counter],DESC))",
              "VAR _topRace = SELECTCOLUMNS(_topRow,[Sub-Dimension])",
              "VAR _topRaceMembers = SELECTCOLUMNS(_topRow,[@counter])",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText'>",
              "        <text y='10%'>",
              "            They work in <tspan class='bolder'>\"& _counter &\"</tspan> professions",
              "        </text>",
              "        <text y='22.5%'>",
              "           and mostly they are <tspan class='bolder'>\"&_topRace&\"</tspan><tspan class='smallerItalic'> (\"&_topRaceMembers&\")</tspan>.",
              "        </text>",
              "    </g>\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _content & _svgEnding"
            ],
            "lineageTag": "901fd391-ff5d-42ab-879b-6c87c8fbd39b"
          },
          {
            "name": "Slope KPI Chart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _tbl = ",
              "    ADDCOLUMNS(",
              "        ADDCOLUMNS(",
              "            SUMMARIZE('Table','Table'[Dimension]),",
              "            \"@vl\", [Sum (2023)],",
              "            \"@vlFive\", [Sum (2022)]),",
              "            \"@change\",[@vlFive]-[@vl]",
              "        )",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 250 // Height size of the SVG",
              "VAR _padding = 15",
              "VAR _ballsRadius = 5",
              "",
              "VAR _leftXCategory = \"2022\"",
              "VAR _rightXCategory = \"2023\"",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _green = \"#658E95\"",
              "VAR _red = \"#D64550\"",
              "VAR _grey = \"#EDEBE9\"",
              "VAR _lightGrey = \"#F0F0F0\"",
              "VAR _darkGrey = \"#CCCCCC\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "VAR _style = \"",
              "<style>",
              "text{",
              "    font-family: Segoe UI;",
              "}",
              ".greyText{",
              "     fill: \"&_darkGrey&\";",
              "}",
              ".middleText{",
              "    text-anchor: middle; ",
              "    font-size: 10;",
              "}",
              ".linedText{",
              "    dominant-baseline: middle; ",
              "    font-size: 10;",
              "}",
              ".bolder{",
              "    font-weight: bold;",
              "} ",
              ".baseLines{",
              "    stroke-width: 2;",
              "    stroke: \"&_lightGrey&\"; ",
              "    stroke-dasharray: 5,5;",
              "}",
              ".lineStroke{",
              "    stroke-width: 3;",
              "}",
              "</style>\"",
              "",
              "/* CALCULATION */",
              "VAR _doublePadding = _padding*2",
              "VAR _halfPadding = _padding/2",
              "VAR _usableHeight = _height-_doublePadding*2",
              "VAR _textYPostion = _usableHeight+_doublePadding",
              "VAR _betweenLineSpacer = _doublePadding*3",
              "VAR _topRow = INDEX(1, _tbl, ORDERBY(MAX([@vl],[@vlFive]),DESC))",
              "VAR _bottomRow = INDEX(1, _tbl, ORDERBY(MAX([@vl],[@vlFive]),ASC))",
              "VAR _maxValue = MAXX(_topRow,MAX([@vl],[@vlFive]))",
              "VAR _maxx = _maxValue*1.1",
              "VAR _maxC = MAXX(_tbl,[@change])",
              "VAR _minValue = MINX(_bottomRow,MIN([@vl],[@vlFive]))",
              "VAR _minx = _minValue*0.6",
              "VAR _minC = MINX(_tbl,[@change])",
              "VAR _diff = (_maxx-_minx)",
              "VAR _baseTexts =",
              "    VAR _topOfLine = (1-DIVIDE(_maxValue-_minx,_diff))*_usableHeight+_halfPadding",
              "    VAR _bottomOfLine = (1-DIVIDE(_minValue-_minx,_diff))*_usableHeight+_halfPadding",
              "    RETURN",
              "    \"<g class='middleText greyText'>",
              "        <text x='\"&_doublePadding&\"' y='\"&_textYPostion&\"'>\"&_leftXCategory&\"</text>",
              "        <text x='\"&_betweenLineSpacer&\"' y='\"&_textYPostion&\"'>\"&_rightXCategory&\"</text>",
              "    </g>",
              "    <g class='baseLines'>",
              "        <line x1='\"&_doublePadding&\"' x2='\"&_doublePadding&\"' y1='\"&_topOfLine&\"' y2='\"&_bottomOfLine&\"'/>",
              "        <line x1='\"&_betweenLineSpacer&\"' x2='\"&_betweenLineSpacer&\"' y1='\"&_topOfLine&\"' y2='\"&_bottomOfLine&\"'/>",
              "    </g>\"",
              "VAR _circles =",
              "    CONCATENATEX(FILTER(_tbl,NOT [@change] IN {_maxC,_minC}),",
              "        VAR _color = SWITCH([@change],_maxC,_green,_minC,_red,_grey)",
              "        VAR _yOne = (1-DIVIDE([@vl]-_minx,_diff))*_usableHeight+_halfPadding",
              "        VAR _yTwo = (1-DIVIDE([@vlFive]-_minx,_diff))*_usableHeight+_halfPadding",
              "        RETURN",
              "        \"<circle cx='\"&_doublePadding&\"' cy='\"&_yOne&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<circle cx='\"&_betweenLineSpacer&\"' cy='\"&_yTwo&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<line class='lineStroke' x1='\"&_doublePadding&\"' x2='\"&_betweenLineSpacer&\"' y1='\"&_yOne&\"' y2='\"&_yTwo&\"' stroke='\"&_color&\"'/>\"",
              "        & IF(_color<>_grey,",
              "        \"<text class='bolderLinedText' x='\"&_betweenLineSpacer+_padding&\"' y='\"&_yTwo&\"' fill='\"&_color&\"'>\"&[Dimension]&\"</text>\",\"\"))",
              "VAR _circlesUps =",
              "    CONCATENATEX(FILTER(_tbl, [@change] IN {_maxC,_minC}),",
              "        VAR _color = SWITCH([@change],_maxC,_green,_minC,_red,_grey)",
              "        VAR _div = DIVIDE([@vlFive],[@vl])-1",
              "        VAR _resultTexts = ",
              "            SWITCH(",
              "                [@change],",
              "                _maxC,\"increased by \",",
              "                _minC,\"decreased by \"",
              "            )&\"<tspan class='bolder' fill='\"&_color&\"'>\"&FORMAT(_div,\"0.0%;0.0%\")&\"</tspan>\"",
              "        VAR _yOne = (1-DIVIDE([@vl]-_minx,_diff))*_usableHeight+_halfPadding",
              "        VAR _yTwo = (1-DIVIDE([@vlFive]-_minx,_diff))*_usableHeight+_halfPadding",
              "        RETURN",
              "        \"<circle cx='\"&_doublePadding&\"' cy='\"&_yOne&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<circle cx='\"&_betweenLineSpacer&\"' cy='\"&_yTwo&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<line class='lineStroke' x1='\"&_doublePadding&\"' x2='\"&_betweenLineSpacer&\"' y1='\"&_yOne&\"' y2='\"&_yTwo&\"' stroke='\"&_color&\"'/>\"",
              "        & IF(_color<>_grey,",
              "        \"<text class='linedText' x='\"&_betweenLineSpacer+_padding&\"' y='\"&IF([@change]=_maxC,\"45%\",\"55%\")&\"' fill='\"&_darkGrey&\"'><tspan class='bolder' fill='\"&_color&\"'>\"&[Dimension]&\"</tspan> \"&_resultTexts&\"</text>\",\"\"))",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _baseTexts &_circles & _circlesUps & _svgEnd",
              "RETURN",
              "   _result"
            ],
            "lineageTag": "1c55942f-0cf8-4a09-b92e-708b271da829"
          },
          {
            "name": "Progress Simple bar chart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _total = [Sum (2022)]  // Will be used as a target",
              "VAR _value = [Sum (2023)] // Will be used as a current value",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#242425\" // Darkgrey Color",
              "",
              "VAR _stateColor = IF(_total>_value,_negative,_positive)",
              "",
              "/* SVG DECLARTIONS */",
              "// BASIC SVG DECLARATION",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* STYLE DECLARATIONS */",
              "VAR _style = \"",
              "<style>",
              "text{",
              "    font-family: Segoe UI;",
              "    dominant-baseline: middle;",
              "    text-anchor: middle;",
              "}",
              ".progressBar{",
              "    fill: \"&_stateColor&\";",
              "}",
              ".endLine{",
              "    stroke: \"&_darkGrey&\";",
              "    stroke-width: 3;",
              "    stroke-linecap: round;",
              "    stroke-dasharray: 2.5 5;",
              "}",
              ".mainText{",
              "    fill: \"&_stateColor&\";",
              "    font-size: 125%;",
              "    font-weight: bold;",
              "}",
              ".supportText{",
              "    fill:#BBB;",
              "    font-size: 100%;",
              "}",
              "</style>\"",
              "",
              "/* CALCULATION */",
              "// INSERT YOUR CALCULATION HERE",
              "VAR _doublePadding = (_paddning*2)",
              "VAR _usableWidth= _width-(_doublePadding*2)",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _yStartPosition = _height*0.50",
              "VAR _yEndPosition = _usableHeight*0.25",
              "VAR _barWidth = IF(_total>=_value,DIVIDE(_value,_total)*_usableWidth,_usableWidth)",
              "VAR _linePosition = IF(_total>=_value,_width-_doublePadding,DIVIDE(_total,_value)*_usableWidth)",
              "VAR _bar = \"<rect class='progressBar' x='\"&_doublePadding&\"' y='\"&_yStartPosition&\"' width='\"&_barWidth&\"' height='\"&_yEndPosition&\"' rx='1.5%' />\"",
              "VAR _endLine = \"<line class='endLine' x1='\"&_linePosition&\"' x2='\"&_linePosition&\"' y1='\"&_yStartPosition*0.95&\"' y2='\"&(_yStartPosition+_yEndPosition)*1.05&\"' />\"",
              "VAR _texts = ",
              "    \"<text class='mainText' x='50%' y='\" &_yStartPosition*0.60&\"'>\"&FORMAT(DIVIDE(_value,_total),\"0.0%\")&\" ~ \"&IF((_value-_total)<0,\"Not filled\",\"Filled\")&\"</text>",
              "    <text class='supportText' x='50%' y='\" &_yStartPosition*0.825&\"'>Current: \"&_value&\" | Target: \"&_total&\"</text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _bar & _texts & _endLine & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "dc313c4a-8e08-46bf-a9a4-c430139a0ddf"
          },
          {
            "name": "Progress More Complex bar chart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _total = [Sum (2022)]  // Will be used as a target",
              "VAR _value = [Sum (2023)] // Will be used as a current value",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#242425\" // Darkgrey Color",
              "",
              "VAR _stateColor = IF(_total>_value,_negative,_positive)",
              "",
              "/* SVG DECLARTIONS */",
              "// BASIC SVG DECLARATION",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* STYLE DECLARATIONS */",
              "VAR _style = \"",
              "<style>",
              "text{",
              "    font-family: Segoe UI;",
              "    dominant-baseline: middle;",
              "    text-anchor: middle;",
              "}",
              ".progressBar{",
              "    fill: #CCC;",
              "}",
              ".endLine{",
              "    stroke: \"&_darkGrey&\";",
              "    stroke-width: 3;",
              "    stroke-linecap: round;",
              "    stroke-dasharray: 2.5 5;",
              "}",
              ".mainText{",
              "    fill: \"&_stateColor&\";",
              "    font-size: 125%;",
              "}",
              ".supportText{",
              "    fill:#BBB;",
              "    font-size: 100%;",
              "}",
              ".negativeResult{",
              "    fill: url(#negativePattern);",
              "    stroke: \"&_negative&\";",
              "    stroke-width: 1;",
              "    stroke-dasharray: 7 5;",
              "}",
              ".positiveResult{",
              "    fill: \"&_positive&\";",
              "    stroke: none;",
              "}",
              ".negPatternLines{",
              "    fill-opacity: 1;",
              "    stroke: \"&_negative&\";",
              "}",
              ".bolden{",
              "    font-weight: bold;",
              "}",
              "</style>\"",
              "",
              "/* DEFS + PATTERNS DECLARATIONS */",
              "VAR _defs =",
              "\"<defs>",
              "    <pattern id='negativePattern' x='0' y='0' width='10' height='10' patternUnits='userSpaceOnUse'>",
              "        <line class='negPatternLines' x1='10' x2='0' y1='0' y2='10' />",
              "    </pattern>",
              "</defs>\"",
              "",
              "/* CALCULATION */",
              "// INSERT YOUR CALCULATION HERE",
              "VAR _doublePadding = (_paddning*2)",
              "VAR _usableWidth= _width-(_doublePadding*2)",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _yStartPosition = _height*0.50",
              "VAR _yEndPosition = _usableHeight*0.25",
              "VAR _div = DIVIDE(_value,_total)",
              "VAR _divModifiedByWidth = _div*_usableWidth",
              "VAR _barWidth = IF(_total>=_value,_divModifiedByWidth,_usableWidth)",
              "VAR _linePosition = IF(_total>=_value,_width-_doublePadding,DIVIDE(_total,_value)*_usableWidth)",
              "VAR _bar = \"<rect class='progressBar' x='\"&_doublePadding&\"' y='\"&_yStartPosition&\"' width='\"&_barWidth&\"' height='\"&_yEndPosition&\"'/>\"",
              "& ",
              "    IF(_total>_value,",
              "        \"<rect class='negativeResult' x='\"&_doublePadding+_barWidth&\"' y='\"&_yStartPosition&\"' width='\"&_linePosition-(_doublePadding+_barWidth)&\"' height='\"&_yEndPosition&\"' />\",",
              "        \"<rect class='positiveResult' x='\"&_linePosition&\"' y='\"&_yStartPosition&\"' width='\"&_barWidth-_linePosition+_doublePadding&\"' height='\"&_yEndPosition&\"' />\"",
              "    )",
              "VAR _endLine = \"<line class='endLine' x1='\"&_linePosition&\"' x2='\"&_linePosition&\"' y1='\"&_yStartPosition*0.95&\"' y2='\"&(_yStartPosition+_yEndPosition)*1.05&\"' />\"",
              "VAR _texts = ",
              "    \"<text class='mainText bolden' x='50%' y='\" &_yStartPosition*0.60&\"'>\"&FORMAT(_div,\"0.0%\")&\" ~ \"&IF((_value-_total)<0,\"Not filled\",\"Filled\")&\"</text>",
              "    <text class='supportText' x='50%' y='\" &_yStartPosition*0.825&\"'>\"&IF(_value>=_total,\"Over: \", \"Missing: \")&\"<tspan class='bolden'>\"&ABS(_value-_total)&\"</tspan></text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _bar & _texts & _endLine & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "992f445a-d1de-4684-b6d2-a32ad2e5a7e6"
          },
          {
            "name": "Waffle Filling Card",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _val = DIVIDE([Sum (2023)],[Sum (2022)])*100 // INSERT YOUR MEASURE HERE <- OUTPUT OF MEASURE SHOUD BE WHOLE NUMBER BETWEEN 0 AND 100",
              "VAR _space = 5 // SPACE BETWEEN CUBES",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 240 // Height size of the SVG",
              "VAR _padding = 15 // Padding between border and SVG",
              "",
              "/* PRECALCULATIONS */",
              "VAR _doublePadding = _padding*2",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _usableWidth = _width-_doublePadding",
              "VAR _imageSize = MIN(_usableHeight,_usableWidth) // HEIGHT SIZE OF IMAGE",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _nonfilledCubeColor = \"#CCCCCC\" // COLOR OF NON FILLED CUBES",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _filledCubeColor = // COLOR OF FILLED CUBES ",
              "    SWITCH(",
              "        TRUE(),",
              "        _val >= 80, _positive,",
              "        _val > 70, _neutral,",
              "        _negative",
              "        ) ",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height = '\" & _height & \"' width = '\" & _width & \"'>\" ",
              "VAR _svgEnd = \"</svg>\" ",
              "",
              "/* CALCULATION */",
              "VAR _size = 10 // NUMBER OF CUBES IN ONE ROW !!! IF YOU CHANGE THAT YOU NEED TO CHANGE ALSO _cubes._clr !!!",
              "VAR _roundedValue = ROUND(_val,1)",
              "VAR _generateSeries =",
              "    SELECTCOLUMNS ( GENERATESERIES ( 0, ( _size * _size ) - 1, 1 ), \"@vl\", [Value] ) // GENERATING SERIES FROM 0 TO 99",
              "VAR _cubeSize =",
              "    ROUND ( DIVIDE ( _imageSize - ( ( _size + 1 ) * _space ), _size ), 1 )",
              "VAR _cubes =",
              "    CONCATENATEX (",
              "        _generateSeries,",
              "        VAR _mod =",
              "            _size - MOD ( [@vl], _size )",
              "        VAR _rounder =",
              "            _size",
              "                - ROUNDUP ( DIVIDE ( [@vl] + 1, _size ), 0 )",
              "        VAR _cubeXPosition = ( _mod * _cubeSize ) + ( _space * _mod ) - ( _cubeSize + _space ) // preparing X postion of cube",
              "        VAR _cubeYPosition = ( _rounder * _cubeSize ) + ( _space * _rounder + 1 ) // preparing Y postion of cube",
              "        VAR _cubes =",
              "            SWITCH(TRUE(),",
              "                _val >= [@vl] + 1, ",
              "                \"<rect x='\" & _cubeXPosition+_padding & \"' y='\" & _cubeYPosition+_padding & \"' height='\" & _cubeSize & \"' width='\" & _cubeSize & \"' fill='\" & _filledCubeColor & \"' />\", ",
              "                _val >= [@vl] && _val <= [@vl] + 1, ",
              "                VAR _positionModificator = _val-[@vl]",
              "                VAR _x = _cubeXPosition+_padding",
              "                VAR _y = _cubeYPosition+_padding",
              "                RETURN",
              "                    \"<rect x='\" & _x & \"' y='\" & _y & \"' height='\" & _cubeSize & \"' width='\" & _cubeSize & \"' fill='\" & _nonfilledCubeColor & \"' />",
              "                    <rect x='\" & _x+(_cubeSize*(1-_positionModificator)) & \"' y='\" & _y & \"' height='\" & _cubeSize & \"' width='\" & _cubeSize *_positionModificator & \"' fill='\" & _filledCubeColor & \"' />\",",
              "                \"<rect x='\" & _cubeXPosition+_padding & \"' y='\" & _cubeYPosition+_padding & \"' height='\" & _cubeSize & \"' width='\" & _cubeSize & \"' fill='\" & _nonfilledCubeColor & \"' />\"",
              "                 ) // assigning color to cube",
              "        RETURN",
              "            _cubes",
              "    )",
              "VAR _text =",
              "    VAR _rounder =",
              "        _size - ROUNDUP ( DIVIDE ( _val, _size ), 0 )",
              "    VAR _textYPosition = ( _rounder * _cubeSize ) + ( _space * _rounder + 1 ) + ( ( _cubeSize + _space ) / 2 )",
              "    RETURN",
              "        \"<text x='\" & _imageSize - _space +_padding & \"' y='\" & _textYPosition + _padding & \"' fill='\" & _filledCubeColor & \"' font-family='Segoe UI' alignment-baseline='middle' font-weight='bold' font-size='95%'>🡄 \" & _roundedValue & \"%</text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _cubes & _text & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "08b0f97c-90f4-4843-b291-570d579d57a7"
          },
          {
            "name": "Waffle Icon Filling Card",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _val = (DIVIDE([Sum (2023)],[Sum (2022)])*0.75)*100+0.2 // INSERT YOUR MEASURE HERE <- OUTPUT OF MEASURE SHOUD BE WHOLE NUMBER BETWEEN 0 AND 100",
              "VAR _space = 5 // SPACE BETWEEN CUBES",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 240 // Height size of the SVG",
              "VAR _padding = 15 // Padding between border and SVG",
              "",
              "/* PRECALCULATIONS */",
              "VAR _doublePadding = _padding*2",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _usableWidth = _width-_doublePadding",
              "VAR _imageSize = MIN(_usableHeight,_usableWidth) // HEIGHT SIZE OF IMAGE",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _filledCubeColor = // COLOR OF FILLED CUBES ",
              "    SWITCH(",
              "        TRUE(),",
              "        _val >= 80, _positive,",
              "        _val > 70, _neutral,",
              "        _negative",
              "        ) ",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height = '\" & _height & \"' width = '\" & _width & \"'>\" ",
              "VAR _svgEnd = \"</svg>\" ",
              "",
              "/* ICONS DECLARATIONS */",
              "VAR _defs = ",
              "    \"<defs>",
              "        <svg id='skeleton' viewBox='0 0 90 90' xmlns:space='preserve'>",
              "  <defs>",
              "    <filter id='f1' x='-50%' y='-50%' width='200%' height='200%'>",
              "      <feGaussianBlur in='SourceGraphic' stdDeviation='2' result='blur' />",
              "      <feColorMatrix in='blur' type='matrix' values='0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 -10' result='goo' />",
              "      <feBlend in='SourceGraphic' in2='goo' />",
              "    </filter>",
              "  </defs>",
              "  <g filter='url(#f1)'><svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 90 90' data-tags='body'>",
              "      <g class='bones' stroke='#000' stroke-width='2.25'>",
              "        <path fill='#ffffff' data-layer='skeleton/bones' d='M43.2 39.6h3.6v36h-3.6z' />",
              "        <path",
              "          d='M45 81l-1.8-1.8-1.8-3.6 1.8-1.8h3.6l1.8 1.8-1.8 3.6zM41.4 63.537c.624 1.899.58 3.692 0 5.4h7.2c-.503-1.77-.574-3.566 0-5.4zM41.4 51.794c.624 1.898.58 3.691 0 5.4h7.2c-.503-1.77-.574-3.567 0-5.4zM41.4 42.104c.624 1.899.58 3.692 0 5.4h7.2c-.503-1.77-.574-3.566 0-5.4z'",
              "          fill='#ffffff' data-layer='skeleton/bones' />",
              "        <path",
              "          d='M45 9C28.8 9 14.4 19.8 11.062 33c-1.38 5.461 2.558 8.44 8.75 10.062v5.532h50.376v-5.532c6.192-1.623 10.13-4.6 8.75-10.062C75.6 19.8 61.2 9 45 9z'",
              "          fill='#ffffff' data-layer='skeleton/bones' />",
              "        <path d='M27 41.4v7.2m7.2-7.2v7.2m7.2-7.2v7.2m7.2-7.2v7.2m7.2-7.2v7.2m7.2-7.2v7.2' fill='none' />",
              "        <path",
              "          d='M22.594 50.217a4.5 4.5 0 0 0-4.5 4.5c0 1.021.363 1.932.937 2.687-.574.755-.937 1.666-.937 2.688a4.5 4.5 0 0 0 8.906.906h36a4.5 4.5 0 0 0 8.906-.906c0-1.022-.363-1.933-.937-2.688.574-.755.937-1.666.937-2.687A4.5 4.5 0 0 0 63 53.81H27a4.5 4.5 0 0 0-4.406-3.593z'",
              "          fill='#ffffff' data-layer='skeleton/bones' />",
              "        <path",
              "          d='M31.594 64.819a4.5 4.5 0 0 0-4.5 4.5c0 1.022.363 1.932.937 2.687-.574.756-.937 1.666-.937 2.688A4.5 4.5 0 0 0 36 75.6h18a4.5 4.5 0 0 0 8.906-.906c0-1.022-.363-1.932-.937-2.688.574-.755.937-1.665.937-2.687A4.5 4.5 0 0 0 54 68.413H36a4.5 4.5 0 0 0-4.406-3.594z'",
              "          fill='#ffffff' data-layer='skeleton/bones' />",
              "      </g>",
              "      <g class='sockets' fill='#000000' stroke='#000' stroke-width='2.25'>",
              "        <path",
              "          d='M34.179 26.377c-.529 2.834-3.254 5.131-6.088 5.131s-4.703-2.297-4.175-5.131c.529-2.834 3.254-5.132 6.088-5.132s4.703 2.298 4.175 5.132zM55.959 26.377c.528 2.834 3.254 5.131 6.088 5.131s4.703-2.297 4.174-5.131c-.528-2.834-3.254-5.132-6.088-5.132s-4.703 2.298-4.174 5.132z'",
              "          data-layer='skeleton/sockets' />",
              "      </g>",
              "    </svg></g>",
              "</svg>",
              "    <svg id='goblin' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 90 90' xml:space='preserve'>",
              "  <defs>",
              "    <filter id='f1' x='-50%' y='-50%' width='200%' height='200%'>",
              "      <feGaussianBlur in='SourceGraphic' stdDeviation='2' result='blur'/>",
              "      <feColorMatrix in='blur' type='matrix' values='0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 -10' result='goo'/>",
              "      <feBlend in='SourceGraphic' in2='goo'/>",
              "    </filter>",
              "  </defs><g filter='url(#f1)'><svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 90 90' data-tags='clothing'><defs><linearGradient id='d-rmefh-a'><stop offset='0'/><stop offset='1' stop-opacity='0'/></linearGradient></defs><path d='M48 73.938c-2.432 2.403-5.47 4.653-9.281 6.5A36.03 36.03 0 0 0 45 81c3.868 0 7.602-.59 11.094-1.719-3.182-1.678-5.861-3.506-8.094-5.343z' fill='#b4b4b4' data-layer='leaf-garment/shirt' stroke='#000' stroke-width='2.25' stroke-linecap='round'/><g class='leaf-right' fill='#31542D' stroke='#000'><path d='M79.219 50.094C71.92 52.449 59.745 54 45.906 54c-2.527 0-4.977-.058-7.375-.156l-.718 7.344S46.8 84.6 84.6 86.4c1.8-9-3.6-35.994-3.6-35.994z' data-layer='leaf-garment/leaf-right' stroke-width='2.25'/><path d='M64.8 61.2c3.6 14.4 19.8 25.2 19.8 25.2' data-layer='leaf-garment/leaf-right' stroke-width='2.25' stroke-linecap='round'/><path d='M73.167 75.09c2.667-3.103 6.597-2.854 6.597-2.854M76.279 79.2c-2.479 0-3.5 2.336-3.5 2.336M69.296 70.028c-5.4 1.8-7.2 5.4-7.2 5.4M66.6 66.6c3.6-5.4 10.8-5.4 10.8-5.4' data-layer='leaf-garment/leaf-right' stroke-width='1.125' stroke-linecap='round'/></g><g class='leaf-left' fill='#31542D' stroke='#000'><path d='M9 48.594s-5.4 18.006-3.594 36C55.8 90 57.594 54 57.594 54l-.375-.375c-3.59.234-7.38.375-11.313.375-16.282 0-30.285-2.14-36.718-5.219.114-.283-.163-.162-.188-.187z' data-layer='leaf-garment/leaf-left' stroke-width='2.25'/><path d='M28.8 59.4C23.4 70.2 7.2 82.8 7.2 82.8' data-layer='leaf-garment/leaf-left' stroke-width='2.25' stroke-linecap='round'/><path d='M15.915 75.04C12.982 72 9 73.8 9 73.8M18.636 71.773c8.364.227 11.326 4.28 11.326 4.28M23.025 67.976c-3.936-5.26-11.136-3.46-11.136-3.46M25.914 63.096C36 63 40.847 68.854 40.847 68.854' data-layer='leaf-garment/leaf-left' stroke-width='1.125' stroke-linecap='round'/></g></svg><svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 90 90' data-tags='body+fantasy'><path d='M9.113 9c-1.8 3.6-3.02 9.495-3.625 14.406-.734 5.955-2.832 12.71 0 18 .55 1.027 2.054 1.953 3.343 2.625-.009.325-.03.642-.03.969 0 19.882 16.117 36 36 36 19.881 0 36-16.118 36-36 0-.274.005-.54 0-.812 1.344-.674 2.998-1.67 3.593-2.782 2.831-5.29.733-12.045 0-18C83.789 18.496 82.6 12.6 80.8 9c-1.8 3.6-2.789 9.202-3.594 10.812-1.012 2.025-1.462 4.587-1.656 6.47C69.23 15.921 57.823 9 44.8 9c-12.862 0-24.133 6.76-30.5 16.906-.213-1.84-.649-4.203-1.594-6.094C11.901 18.202 10.913 12.6 9.113 9z' fill='#809F5A' data-layer='elf/body' stroke='#000' stroke-width='2.25' stroke-linecap='round'/></svg><svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 90 90' data-tags='hair'><defs><linearGradient id='d-f4ULu-a'><stop offset='0'/><stop offset='1' stop-opacity='0'/></linearGradient></defs><path d='M43.2 9s-18-5.4-28.8 10.8c-1.8 3.6-2.076 8.329-9 10.8 0 0 0 1.8 3.6 3.6 0 0 0 1.8-3.6 5.4 3.6 3.6 10.8-7.2 10.8-7.2L18 36s10.8-5.4 14.4-10.8c1.8 1.8 3.6 3.6 3.6 7.2C50.4 27 50.4 19.8 50.4 19.8l9 7.2s3.6-1.8 3.6-5.4c3.6 1.8 7.2 9 7.2 9l1.8-5.4c3.6 7.2 10.8 5.4 10.8 5.4-1.8-1.8-7.2-10.8-7.2-10.8C61.2 1.8 43.2 9 43.2 9z' fill='#0D5704' data-layer='relaxed-hair/hair' stroke='#000' stroke-width='2.25'/></svg><svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 90 90' data-tags='clothing+modern'><path d='M9.18 48.781c1.887 18.108 17.205 32.22 35.813 32.22 18.334 0 33.474-13.713 35.718-31.438C73.66 52.208 60.741 54 45.9 54c-16.282 0-30.286-2.14-36.719-5.219z' fill='#6D6A65' data-layer='bulletproof-vest/shirt' stroke='#000' stroke-width='2.25' stroke-linecap='round'/><g class='tie' fill='#b4b4b4' stroke='#000' stroke-width='2.25'><path d='M45.36 57.24h-2.427l-1.618 13.907 4.045 6.954 4.045-6.954-1.618-13.907z' data-layer='bulletproof-vest/tie'/><path d='M41.399 53.906c-.064 1.25-.045 2.588.295 3.344.76 1.692 3.677 2.5 3.677 2.5s2.894-.808 3.654-2.5c.34-.756.36-2.094.295-3.344-1.17.044-2.354.094-3.563.094-1.479 0-2.94-.029-4.358-.094z' data-layer='bulletproof-vest/tie'/></g><path style='marker:none' d='M28.969 53.156c-.01 7.912-4.012 14.604-9.594 17.125C25.905 76.896 34.971 81 45 81c10.059 0 19.154-4.129 25.688-10.781-5.468-2.561-9.376-9.141-9.438-16.906-2.65.244-5.443.417-8.344.53-.088 4.672-3.412 8.438-7.531 8.438-4.129 0-7.488-3.782-7.563-8.468-3.08-.14-6.062-.371-8.843-.657z' fill='#B1564D' data-layer='bulletproof-vest/vest' color='#000' stroke='#000' stroke-width='2.25' stroke-linejoin='round' overflow='visible'/><g class='vest-pads' fill='#b4b4b4' color='#000' stroke='#000' stroke-width='2.25' stroke-linejoin='round'><path style='marker:none' d='M61.844 58.313l-4.282 2.468c-2.1 1.213-2.857 3.849-1.687 5.875 1.17 2.027 3.836 2.682 5.938 1.469L65.5 66c-1.684-2.117-2.962-4.737-3.656-7.688zM28.188 59.063c-.796 2.907-2.174 5.47-3.938 7.5l2.688 1.562c2.1 1.213 4.767.558 5.937-1.469 1.17-2.026.414-4.662-1.688-5.875l-3-1.718z' data-layer='bulletproof-vest/vest-pads' overflow='visible'/></g></svg></g></svg>",
              "    </defs>\"",
              "",
              "/* CALCULATION */",
              "VAR _size = 10 // NUMBER OF CUBES IN ONE ROW !!! IF YOU CHANGE THAT YOU NEED TO CHANGE ALSO _cubes._clr !!!",
              "VAR _roundedValue = ROUND(_val,1)",
              "VAR _generateSeries =",
              "    SELECTCOLUMNS ( GENERATESERIES ( 0, ( _size * _size ) - 1, 1 ), \"@vl\", [Value] ) // GENERATING SERIES FROM 0 TO 99",
              "VAR _cubeSize =",
              "    ROUND ( DIVIDE ( _imageSize - ( ( _size + 1 ) * _space ), _size ), 1 )",
              "VAR _cubes =",
              "    CONCATENATEX (",
              "        _generateSeries,",
              "        VAR _mod =",
              "            _size - MOD ( [@vl], _size )",
              "        VAR _rounder =",
              "            _size",
              "                - ROUNDUP ( DIVIDE ( [@vl] + 1, _size ), 0 )",
              "        VAR _cubeXPosition = ( _mod * _cubeSize ) + ( _space * _mod ) - ( _cubeSize + _space ) // preparing X postion of cube",
              "        VAR _cubeYPosition = ( _rounder * _cubeSize ) + ( _space * _rounder + 1 ) // preparing Y postion of cube",
              "        VAR _cubes =",
              "            SWITCH(TRUE(),",
              "                _val >= [@vl] + 1, ",
              "                \"<use href='#goblin' x='\" & _cubeXPosition+_padding & \"' y='\" & _cubeYPosition+_padding & \"' height='\" & _cubeSize & \"' width='\" & _cubeSize & \"' />\", ",
              "                _val >= [@vl] && _val <= [@vl] + 1, ",
              "                VAR _positionModificator = _val-[@vl]",
              "                VAR _update = 1-_positionModificator",
              "                VAR _x = _cubeXPosition+_padding",
              "                VAR _y = _cubeYPosition+_padding",
              "                RETURN",
              "                    \"<use href='#skeleton' x='\" & _x & \"' y='\" & _y & \"' height='\" & _cubeSize*_update & \"' width='\" & _cubeSize*_update & \"' />",
              "                    <use href='#goblin' x='\" & _x+(_cubeSize*_update) & \"' y='\" & _y+(_cubeSize*_update) & \"' height='\" & _cubeSize*_positionModificator & \"' width='\" & _cubeSize*_positionModificator & \"' />\",",
              "                \"<use href='#skeleton' x='\" & _cubeXPosition+_padding & \"' y='\" & _cubeYPosition+_padding & \"' height='\" & _cubeSize & \"' width='\" & _cubeSize & \"' />\"",
              "                 ) // assigning color to cube",
              "        RETURN",
              "            _cubes",
              "    )",
              "VAR _text =",
              "    VAR _rounder =",
              "        _size - ROUNDUP ( DIVIDE ( _val, _size ), 0 )",
              "    VAR _textYPosition = ( _rounder * _cubeSize ) + ( _space * _rounder + 1 ) + ( ( _cubeSize + _space ) / 2 )",
              "    RETURN",
              "        \"<text x='\" & _imageSize - _space +_padding & \"' y='\" & _textYPosition + _padding & \"' fill='\" & _filledCubeColor & \"' font-family='Segoe UI' alignment-baseline='middle' font-weight='bold' font-size='95%'>🡄 \" & _roundedValue & \"%</text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _defs & _cubes & _text & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "020e68df-c941-4f02-acbc-579be8a2588e"
          },
          {
            "name": "Line Chart Decisions",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "// INSERT YOUR SETUP VARIABLES HERE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 230 // Height size of the SVG",
              "VAR _padding = 15",
              "VAR _ballsRadius = 5",
              "",
              " ",
              "VAR _preparedTbl = ",
              "    ADDCOLUMNS(",
              "        SELECTCOLUMNS(SUMMARIZE('Table','Table'[Quantitative]),\"@xAxis\",[Quantitative]),",
              "        \"@vl\", [Sum]",
              "    )",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#808080\" // Will be used for all text",
              "VAR _targetLineColor = \"#A8A8A8\" // Will be used for target line",
              "",
              "/* PRECALCULATIONS */",
              "VAR _maxValue = MAXX(_preparedTbl,[@vl])",
              "VAR _target = AVERAGEX(_preparedTbl,[@vl])",
              "VAR _counter = COUNTROWS(_preparedTbl)",
              "VAR _half = _counter/2",
              "VAR _targetFulfillment = COUNTROWS(FILTER(_preparedTbl,[@vl]>=_target))",
              "",
              "/* STYLE DECLARATIONS */",
              "VAR _style = \"<style> ",
              "text{",
              "    font-size:95%;",
              "    font-family: Segoe UI;",
              "    dominant-baseline: hanging;",
              "    fill:\"&_darkGrey&\";",
              "}",
              ".bolder{",
              "    font-weight: bold;",
              "}",
              ".italic{",
              "    font-style: italic;",
              "}",
              ".lineChart{",
              "    stroke:\"&_targetLineColor&\";",
              "    stroke-width:2.5;",
              "    fill: none;",
              "}",
              ".positiveBar{",
              "    fill:\"&_positive&\";",
              "    opacity: 0.15;",
              "}",
              ".stateColor{",
              "    fill:\"&IF(_targetFulfillment>=_half,_positive,_negative)&\"",
              "}",
              ".negativeResult{fill:\"&_negative&\"}",
              ".positiveResult{fill:\"&_positive&\"}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "// BASIC SVG DECLARATION",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' width='\"&_width&\"' height='\"&_height&\"'>\"",
              "",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _doubePadding = _padding*2",
              "VAR _updatedHeight = (_height-_doubePadding)",
              "VAR _usableWidth = _width-_doubePadding",
              "VAR _scale = 0.45",
              "VAR _usableHeight = _updatedHeight*_scale",
              "VAR _revertedHeight = _updatedHeight*(1-_scale)",
              "VAR _targetHeight = ((_usableHeight-(DIVIDE(_target,_maxValue))*_usableHeight)+_revertedHeight)-_usableHeight",
              "VAR _rowsCounter = COUNTROWS(_preparedTbl)",
              "VAR _spaceBetweenPoitns = _usableWidth/_rowsCounter",
              "VAR _totalSum = SUMX(_preparedTbl,[@vl])",
              "VAR _targetSum = ROUND(_target,1)*_counter",
              "",
              "VAR _lineChart =",
              "\"<path class='lineChart' d='\" & ",
              "    CONCATENATEX(_preparedTbl,",
              "        VAR _rowNumber = ROWNUMBER(_preparedTbl,ORDERBY([@xAxis],ASC BLANKS DEFAULT))",
              "        VAR _xPostion = (_rowNumber*_spaceBetweenPoitns)",
              "        VAR _yPosition = (_usableHeight-(([@vl]/_maxValue)*_usableHeight))+_revertedHeight",
              "        RETURN",
              "        IF(_rowNumber=1,\"M \",\" L \") & _xPostion & \" \" & _yPosition) & \"' />\"",
              "VAR _positiveStack = ",
              "\"<rect class='positiveBar' x='\"&_padding&\"' y='\"&_usableHeight&\"' width='\"&_usableWidth&\"' height='\"&_targetHeight&\"'  />\"",
              "VAR _txt = \"",
              "    <text x='\"&_padding&\"' y='\"&_padding&\"'><tspan class='stateColor'>\"&COUNTROWS(FILTER(_preparedTbl,[@vl]>=_target))&\"x</tspan> was target hit <tspan class='italic'>~ \"&FORMAT(DIVIDE(_targetFulfillment,_counter),\"0.0%\")&\"</tspan></text>",
              "    <text x='\"&_padding&\"' y='\"&_padding*2.5&\"'>Monthly target was \"&ROUND(_target,1)&\", so \"&_targetSum&\" in total.</text>",
              "    <text x='\"&_padding&\"' y='\"&_padding*4&\"'>Total sales were <tspan class='stateColor'>\"&_maxValue&\"</tspan> ~ \"&IF(_targetSum>_maxValue,\"<tspan class='negativeResult bolder'>CLAIM NOT APPROVED</tspan>\", \"<tspan class='positiveResult bolder'>CLAIM APPROVED</tspan>\")&\"</text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _positiveStack & _lineChart & _txt & _svgEnd",
              "RETURN",
              "    _result "
            ],
            "lineageTag": "88ff7e58-2341-4ff0-9173-85efae06b962"
          },
          {
            "name": "KPI Target Checker",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "/* SETUP */",
              "// INSERT YOUR SETUP VARIABLES HERE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 230 // Height size of the SVG",
              "VAR _padding = 15",
              "VAR _boxSize = 25",
              " ",
              "VAR _preparedTbl = ",
              "    SELECTCOLUMNS(",
              "        {",
              "            (1, [Sum (2023)],[Sum (2022)],\"#\"),",
              "            (2, DIVIDE([Sum (2023)],[Sum (2022)]), 0.70,\"0.0%\"),",
              "            (3, CALCULATE([Sum],'Table'[Dimension]=\"Elves\"),CALCULATE([Sum],'Table'[Dimension]=\"Orcs\"),\"#\"),",
              "            (4, DIVIDE(CALCULATE([Sum],'Table'[Dimension]=\"Goblins\"),[Sum]),0.30,\"0.0%\"),",
              "            (5, DIVIDE(CALCULATE([Sum],'Table'[Sub-Dimension]=\"Monks\"),[Sum]),0.54,\"0.0%\")",
              "        },",
              "    \"@id\",[Value1],",
              "    \"@actValue\",[Value2],",
              "    \"@targetValue\",[Value3],",
              "    \"@format\", [Value4]",
              "    )",
              "",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#808080\" // Will be used for box border and texts",
              "",
              "/* STYLE DECLARATIONS */",
              "VAR _style =",
              "\"<style>",
              "text{",
              "    font-family: Segoe UI;",
              "    dominant-baseline: middle;",
              "    fill: \"&_darkGrey&\";",
              "}",
              ".positiveText{",
              "    fill: \"&_positive&\";",
              "}",
              ".negativeText{",
              "    fill: \"&_negative&\";",
              "}",
              ".bolder{",
              "    font-weight: bold;",
              "}",
              ".box{",
              "    fill:none;",
              "    stroke: \"&_darkGrey&\";",
              "    stroke-width: 2;",
              "}",
              ".check{",
              "    fill:none;",
              "    stroke:\"&_positive&\";",
              "    stroke-width: 3;",
              "    stroke-linecap: round;",
              "    stroke-linejoin: round;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "// BASIC SVG DECLARATION",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' width='\"&_width&\"' height='\"&_height&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _doubePadding = _padding*2",
              "VAR _usableHeight = (_height-_doubePadding)",
              "VAR _rowsCounter = COUNTROWS(_preparedTbl)",
              "VAR _spaceBetweenPoitns = _usableHeight/_rowsCounter",
              "VAR _boxSegment = (_boxSize/6)",
              "",
              "VAR _checkBoxes =",
              "    CONCATENATEX(_preparedTbl,",
              "        VAR _rowNumber = [@id]-1",
              "        VAR _yPosition = _rowNumber*_spaceBetweenPoitns+_padding",
              "        RETURN",
              "        \"<rect class='box' rx='1%' x='\" & _padding & \"' y='\" & _yPosition & \"' width='\"&_boxSize&\"' height='\"&_boxSize&\"' />\"",
              "        &",
              "        IF([@actValue]>=[@targetValue],\"<path class='check' d='M \"&_padding+_boxSegment&\" \"&_yPosition+(_boxSize/2)&\" L \"&_padding+(_boxSegment*2)&\" \"&_yPosition+(_boxSize*(3/4))&\" L \"&_padding+(_boxSegment*5)&\" \"&_yPosition+(_boxSize*(1/4))&\"' />\",\"\")",
              "        &",
              "        \"<text x='\" & (_padding*2)+_boxSize & \"' y='\" & _yPosition+(_boxSize/2) & \"'>Reached <tspan class='\"&IF([@actValue]>=[@targetValue],\"positiveText\",\"negativeText\")&\" bolder'>\"&FORMAT([@actValue],[@format])&\"</tspan> from targeted <tspan class='bolder'>\"&FORMAT([@targetValue],[@format])&\"</tspan></text>\"",
              "        ,\"\",[@id],DESC)",
              "",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _checkBoxes & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "26e82a6c-10cd-47ad-9b61-5808fdd7b425"
          },
          {
            "name": "Range Progress Card",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _insertedMeasure = ROUND(DIVIDE([Sum (2023)],[Sum (2022)]),2) // Measure that you want to use for generating this visual (its value should be one of categories)",
              "VAR _categories = 10 // Number of categories/marker lines that you want to have",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 230 // Height size of the SVG",
              "VAR _padding = 15",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#242425\" // Darkgrey Color",
              "VAR _lightGrey = \"#CCCCCC\"",
              "VAR _colorDefined = SWITCH(TRUE(),_insertedMeasure>0.66,_positive,_insertedMeasure>0.33,_neutral,_negative)",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style =",
              "\"<style>",
              "text{",
              "    font-family: Segoe UI;",
              "    text-anchor: middle;",
              "}",
              "rect{",
              "    stroke: none;",
              "}",
              ".negativeBar{",
              "    fill: \"&_negative&\";",
              "}",
              ".neutralBar{",
              "    fill: \"&_lightGrey&\";",
              "}",
              ".positiveBar{",
              "    fill: \"&_positive&\";",
              "}",
              ".supportLines{",
              "    stroke: \"&_lightGrey&\";",
              "    stroke-width: 2;",
              "}",
              ".supportText{",
              "    fill: #CCC;",
              "}",
              ".hangText{",
              "    dominant-baseline: hanging;",
              "}",
              ".mainText{",
              "    fill: \"&_colorDefined&\";",
              "}",
              ".claimText{",
              "    font-size: 150%;",
              "    font-weight: bold;",
              "    fill: \"&_colorDefined&\";",
              "}",
              ".mainTextGrey{",
              "    font-size: 150%;",
              "    fill: \"&_lightGrey&\";",
              "}",
              ".triangleColor{",
              "    font-size: 150%;",
              "    dominant-baseline: middle;",
              "    fill: \"&_lightGrey&\";",
              "    stroke: \"&_darkGrey&\";",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' width='\"&_width&\"' height='\"&_height&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _doublePadding = _padding*2",
              "VAR _usableWidth = _width-_doublePadding",
              "VAR _tripledUsableWidth = _usableWidth/3",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _bars =",
              "\"<rect class='negativeBar' x='\"&_padding&\"' y='55%' width='\"&_tripledUsableWidth&\"' height='15%' />",
              "<rect class='neutralBar' x='\"&_tripledUsableWidth+_padding&\"' y='55%' width='\"&_tripledUsableWidth&\"' height='15%' />",
              "<rect class='positiveBar' x='\"&(_tripledUsableWidth*2)+_padding&\"' y='55%' width='\"&_tripledUsableWidth&\"' height='15%' />\"",
              "VAR _movableTriangle = ",
              "    \"<text class='triangleColor' x='\"&_padding+(_usableWidth*IF(_insertedMeasure>1,1,_insertedMeasure))&\"' y='56.125%'>▼</text>\"",
              "VAR _supportTexts = ",
              "    \"<g class='hangText'><text class='supportText' x='\"&_padding+(_tripledUsableWidth/2)&\"' y='75%'>to 33%</text>",
              "    <text class='supportText' x='\"&_padding+(_tripledUsableWidth*1.5)&\"' y='75%'>to 66%</text>",
              "    <text class='supportText' x='\"&_padding+(_tripledUsableWidth*2.5)&\"' y='75%'>to 100%</text></g>\"",
              "VAR _resultText = ",
              "    \"<text class='mainTextGrey' x='50%' y='40%'> we reached <tspan class='mainText'>\"&FORMAT(_insertedMeasure,\"0.0%\")&\"</tspan></text>",
              "    <text class='claimText' x='50%' y='25%'>\"&SWITCH(TRUE(),_insertedMeasure>0.66,\"CLAIM ACCEPTED\",_insertedMeasure>0.33,\"NO ABILITY TO DECIDE\",\"CLAIM NOT ACCEPTED\")&\"</text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _bars & _movableTriangle & _supportTexts & _resultText & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "a1e2d97d-546c-4e98-98ba-6bf9cf51a035"
          },
          {
            "name": "Text Comparer",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _actualQuantity = [Sum (2023)] // Get the actual quantity from the context (Usually it would be measure for the actual year)",
              "VAR _previousQuantity = [Sum (2022)] // Get the previous quantity from the context (Usually it would be measure for the previous year)",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _grey = \"#BBB\"",
              "VAR _lightGrey = \"#CCC\"",
              "VAR _bolderGrey = \"#808080\"",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    dominant-baseline: auto;",
              "    text-anchor: middle;",
              "    font-size:200%;",
              "    fill:\"&IF(_actualQuantity>_previousQuantity,_positive,_negative)&\";",
              "}",
              ".bold{",
              "    font-weight:bold;",
              "}",
              ".subTexts{",
              "    dominant-baseline: hanging;",
              "    font-size:85%;",
              "    fill:\"&_grey&\";",
              "}",
              ".startText{",
              "    text-anchor: start;",
              "}",
              ".endText{",
              "    text-anchor: end;",
              "}",
              ".splitLine{",
              "    stroke:\"&_lightGrey&\";",
              "    stroke-width: 1;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _diff = _actualQuantity-_previousQuantity",
              "VAR _doublePadding = _paddning*2",
              "VAR _usableWidth = _width-_doublePadding",
              "VAR _div = DIVIDE(_actualQuantity,_previousQuantity)-1",
              "VAR _colorForPercentage = ",
              "    SWITCH(TRUE(),",
              "        _div>0,_positive,",
              "        _div<0,_negative,",
              "        _neutral",
              "    )",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText bold'>",
              "        <text y='42.5%' x='50%'>",
              "            \"&_diff&\"",
              "        </text>",
              "    </g>",
              "    <g class='subTexts'>",
              "        <text class='startText' y='57.5%' x='\"&_paddning*1.15&\"'>",
              "            Actual Year: <tspan class='bold'>\"&_actualQuantity&\"</tspan>",
              "        </text>",
              "        <text class='endText' y='57.5%' x='\"&_usableWidth+(_paddning*0.85)&\"'>",
              "            Previous Year: <tspan class='bold'>\"&_previousQuantity&\"</tspan>",
              "        </text>",
              "    </g>\"",
              "VAR _subLine = \"<line class='splitLine' x1='\"&_paddning&\"' x2='\"&_usableWidth+_paddning&\"' y1='50%' y2='50%' />\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _subLine & _content & _svgEnding"
            ],
            "lineageTag": "0f467e9c-6532-4869-9378-a02a2a555507"
          }
        ],
        "partitions": [
          {
            "name": "4. Report-Specific SVG Measures",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}