{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.963.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Table\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "extendedProperties": [
      {
        "name": "TabularEditor_DeploymentMetadata",
        "type": "json",
        "value": {
          "ClientMachine": "DESKTOP-NV69I5J",
          "DeploymentMode": "SaveUI",
          "TabularEditorBuild": "3.9.0.2972",
          "Time": "2023-09-01T09:56:29.4920984+02:00",
          "User": "DESKTOP-NV69I5J\\Klonk-Temp"
        }
      }
    ],
    "relationships": [
      {
        "name": "afb3546c-43d8-48ac-aad4-ca45f6d7bf38",
        "fromColumn": "Month",
        "fromTable": "Table",
        "toColumn": "Date",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Columns",
            "isHidden": true,
            "lineageTag": "b6428db5-956a-46cf-8e0d-f78eb01375b5",
            "sourceColumn": "Dimension",
            "summarizeBy": "none"
          },
          {
            "name": "SubDimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Columns",
            "isHidden": true,
            "lineageTag": "5e30f180-4ec3-494a-b8ad-8c11697dd2f6",
            "sourceColumn": "SubDimension",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Columns",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "90826514-1f5c-4f5a-97ec-cb24d73861b0",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "375a89cb-dd50-4436-8b44-7f963752da6a",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantitative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6707e5e6-d461-4e15-88ef-6d8c60a6e2a5",
            "sourceColumn": "Quantitative",
            "summarizeBy": "sum"
          },
          {
            "name": "Boolean Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Columns",
            "isHidden": true,
            "lineageTag": "2ffa966d-3a78-44d3-9521-f4ea6d5686da",
            "sourceColumn": "Boolean Dimension",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "74c7dcbc-f534-4da1-9c59-174298c17e81",
        "partitions": [
          {
            "name": "Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Dimensions = ",
                "        #table(",
                "            {\"Dimension\", \"SubDimension\"}, ",
                "                {   ",
                "                    {\"Elves\", \"Fighter\"}, ",
                "                    {\"Elves\", \"Rogue\"}, ",
                "                    {\"Elves\", \"Sorcerer\"}, ",
                "                    {\"Goblins\", \"Fighter\"}, ",
                "                    {\"Goblins\", \"Rogue\"}, ",
                "                    {\"Goblins\", \"Sorcerer\"}, ",
                "                    {\"Orcs\", \"Fighter\"}, ",
                "                    {\"Orcs\", \"Rogue\"}, ",
                "                    {\"Orcs\", \"Sorcerer\"}",
                "                }",
                "        ),",
                "",
                "    // All dates in last 2 years YTD",
                "    #\"CY\" = Date.Year(DateTime.FixedLocalNow()),",
                "    #\"PY\" = Date.Year(DateTime.FixedLocalNow()) - 1,",
                "",
                "    DateList2022 = ",
                "        List.Dates(",
                "            #date(#\"PY\", 1, 1), ",
                "            Duration.Days(#date(#\"PY\", 12, 31) - #date(#\"PY\", 1, 1)) + 1, ",
                "            #duration(1, 0, 0, 0)",
                "        ),",
                "",
                "    DateList2023 = ",
                "        List.Dates(",
                "            #date(#\"CY\", 1, 1), ",
                "            Duration.Days(#date(#\"CY\", 8, 31) - #date(#\"CY\", 1, 1)) + 1, ",
                "            #duration(1, 0, 0, 0)",
                "        ),",
                "    ",
                "    CombinedDates = ",
                "        DateList2022 & DateList2023,",
                "    ",
                "    DateTable = ",
                "        Table.FromList(",
                "            CombinedDates,",
                "            Splitter.SplitByNothing(),",
                "            null,",
                "            null,",
                "            ExtraValues.Error",
                "        ),",
                "",
                "    // Cross join dates and dimensions to create base table",
                "    JoinFunction = (DateValue) => Table.AddColumn(Dimensions, \"Month\", each DateValue),",
                "",
                "    CrossJoin = ",
                "        Table.TransformRows(DateTable, (row) => JoinFunction(row[Column1])),",
                "    ",
                "    MergedTable = ",
                "        Table.FromList(",
                "            CrossJoin, ",
                "            Splitter.SplitByNothing(), ",
                "            null, ",
                "            null, ",
                "            ExtraValues.Error",
                "        ),",
                "    ",
                "    FinalTableBase = ",
                "        Table.ExpandTableColumn(",
                "            MergedTable, ",
                "            \"Column1\", ",
                "            {\"Dimension\", \"SubDimension\", \"Month\"}",
                "        ),",
                "",
                "    WithValues = ",
                "        Table.AddColumn(",
                "            FinalTableBase, ",
                "            \"Quantitative\", ",
                "            each ",
                "                let ",
                "                    YearValue = Date.Year([Month]),",
                "                    RandomValue = Number.RoundDown(20 + Number.RandomBetween(-25, 25)),",
                "                    BaseValue = 0 + RandomValue",
                "                in",
                "                    if YearValue = #\"PY\" then",
                "                        BaseValue",
                "                    else if YearValue = #\"CY\" and [Dimension] <> \"Goblins\" then",
                "                        BaseValue * 0.82",
                "                    else if YearValue = #\"CY\" and [Dimension] = \"Goblins\" then",
                "                        BaseValue * 1.07",
                "                    else 0",
                "        ),",
                "",
                "    #\"Changed Type\" = ",
                "        Table.TransformColumnTypes(",
                "            WithValues,",
                "            {",
                "                {\"Quantitative\", Int64.Type},",
                "                {\"Month\", type date},",
                "                {\"SubDimension\", type text},",
                "                {\"Dimension\", type text}",
                "            }",
                "        ),",
                "",
                "    #\"Inserted Year\" = ",
                "        Table.AddColumn(",
                "            #\"Changed Type\", ",
                "            \"Year\", ",
                "            each Date.Year([Month]), ",
                "            Int64.Type",
                "        ),",
                "",
                "    #\"Goblins/Others\" = ",
                "        Table.AddColumn(",
                "            #\"Inserted Year\",",
                "            \"Boolean Dimension\",",
                "            each",
                "                if [#\"Dimension\"] = \"Goblins\" then \"Approved\"",
                "                else \"Unapproved\",",
                "            type text",
                "        )",
                "in",
                "    #\"Goblins/Others\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "2. Report-Specific Objects",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "21661cfde1db4d40be113778b97a84f2"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05cd4f72-d741-444a-8849-796154a583d9",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "bc077534-c5b0-40dd-9fb4-4bad6abc2bd2",
        "measures": [
          {
            "name": "Transparent",
            "displayFolder": "Control Colours",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "\"#00000000\""
            ],
            "isHidden": true,
            "lineageTag": "7af08448-2e99-4e55-a505-8e431865c8dd"
          },
          {
            "name": "Sum (2022; Inverse)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Dynamic Format Strings",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "-[Sum (PY)]"
            ],
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "2ad4db16-6991-4157-8219-d80f6deb39ed"
          },
          {
            "name": "Year Colour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Colours",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "IF(",
              "    SELECTEDVALUE( 'Table'[Year] ) = 2022,",
              "    \"#ece6da\",",
              "    \"#737068\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "7a633807-acfb-4667-bf5f-0f51cfe82c98"
          },
          {
            "name": "Count (Format String)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dynamic Format Strings",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "[Count]"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _Count = [Count]",
                "VAR _Symbol =",
                "    SWITCH(",
                "        TRUE( ),",
                "        _Count > 0, UNICHAR( 10008 ),",
                "        _Count = 0, UNICHAR( 10004 ),",
                "        BLANK( )",
                "    )",
                "RETURN",
                "    \"#,##0 \" & _Symbol"
              ]
            },
            "isHidden": true,
            "lineageTag": "a823e998-d1ef-493c-a9a7-8e843dc61fc9"
          },
          {
            "name": "Waffle Subtitle",
            "displayFolder": "Waffle Chart (DAX Unicode)",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Result = [Sum (% of PY YTD)]",
              "RETURN",
              "    \"Progress: \"",
              "        & FORMAT( _Result, \"#,##0%\" )"
            ],
            "isHidden": true,
            "lineageTag": "fb2bb51a-f88a-49e0-b70d-2c8f9bfe8a11"
          },
          {
            "name": "Dynamic Title (Color Indicator)",
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Result = [Sum (% of PY YTD)]",
              "VAR _Actuals = [Sum (CY YTD)]",
              "VAR _Color =",
              "    IF(",
              "        _Result < 1,",
              "        UNICHAR( 128308 ),",
              "        UNICHAR( 129482 )",
              "    )",
              "RETURN",
              "    _Color & \" Actuals:\"",
              "        & FORMAT( _Actuals, \" #,##0\" )"
            ],
            "isHidden": true,
            "lineageTag": "65c9248a-39c8-491d-87ce-125866b90de7"
          },
          {
            "name": "Rating Subtitle",
            "displayFolder": "Rating (DAX Unicode)",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Rating = [Sum (% of PY YTD)] * 5",
              "RETURN",
              "    \"Rating: \" & FORMAT( _Rating, \"#,##0\" )"
            ],
            "isHidden": true,
            "lineageTag": "22a84017-ed7c-4e73-a82b-0982319caeab"
          },
          {
            "name": "Waffle",
            "displayFolder": "Waffle Chart (DAX Unicode)",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "-- Init",
              "VAR _Actuals = [Sum (CY YTD)]",
              "VAR _Target = [Sum (PY)]",
              "VAR _Perc =",
              "    MIN( 1, DIVIDE( _Actuals, _Target ) )",
              "VAR _TotalCells = 100",
              "VAR _RowLength = 10",
              "VAR _TotalRows =",
              "    CEILING(",
              "        DIVIDE( _TotalCells, _RowLength ),",
              "        1",
              "    )",
              "VAR _FilledCount =",
              "    ROUND( _Perc * _TotalCells, 0 )",
              "",
              "-- Unicode characters",
              "VAR _Filled = UNICHAR( 9632 ) & \" \" -- ■",
              "VAR _Empty = UNICHAR( 9633 ) & \" \"  -- □",
              "-- Figure out the waffle Height x Width etc.",
              "VAR _FullFilledLines =",
              "    INT( _FilledCount / _RowLength )",
              "VAR _FilledPartial =",
              "    MOD( _FilledCount, _RowLength )",
              "VAR _EmptyPartial =",
              "    _RowLength - _FilledPartial",
              "VAR _FullEmptyLines =",
              "    _TotalRows - _FullFilledLines",
              "        - IF( _FilledPartial > 0, 1, 0 )",
              "",
              "-- Result",
              "VAR _Waffle =",
              "    REPT(",
              "        REPT( _Empty, _RowLength )",
              "            & UNICHAR( 10 ),",
              "        _FullEmptyLines",
              "    )",
              "        & IF(",
              "            _FilledPartial > 0,",
              "            REPT( _Filled, _FilledPartial )",
              "                & REPT( _Empty, _EmptyPartial )",
              "                & UNICHAR( 10 ),",
              "            \"\"",
              "        )",
              "        & REPT(",
              "            REPT( _Filled, _RowLength )",
              "                & UNICHAR( 10 ),",
              "            _FullFilledLines",
              "        )",
              "RETURN",
              "    _Waffle"
            ],
            "isHidden": true,
            "lineageTag": "2ccd2bf1-9988-423e-abd0-12ccb403f7ae"
          },
          {
            "name": "Rating",
            "displayFolder": "Rating (DAX Unicode)",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "-- Init",
              "VAR _Actuals = [Sum (CY YTD)]",
              "VAR _Target = [Sum (PY YTD)]",
              "VAR _Perc =",
              "    MIN( 1, DIVIDE( _Actuals, _Target ) )",
              "VAR _MaxStars = 5",
              "VAR _FilledStarsCount =",
              "    INT( _Perc * _MaxStars )",
              "VAR _EmptyStarsCount =",
              "    _MaxStars - _FilledStarsCount",
              "",
              "",
              "-- Unicode characters",
              "VAR _FilledStar = UNICHAR( 9733 )         -- ★",
              "VAR _EmptyStar = UNICHAR( 9734 )          -- ☆",
              "-- Result",
              "VAR _StarRating =",
              "    REPT( _FilledStar, _FilledStarsCount )",
              "        & REPT( _EmptyStar, _EmptyStarsCount )",
              "RETURN",
              "    _StarRating & UNICHAR( 10 )"
            ],
            "isHidden": true,
            "lineageTag": "860209d7-5ea2-4a48-9ea1-2f9e7df39fce"
          },
          {
            "name": "Dynamic Subtitle (Context)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Perc = [Sum (Δ% PY YTD)]",
              "VAR _Color =",
              "    \"   ( \"",
              "        & IF(",
              "            _Perc < 1,",
              "            UNICHAR( 9660 ),",
              "            UNICHAR( 9650 )",
              "        )",
              "VAR _Target = [Sum (PY YTD)]",
              "RETURN",
              "    \"1 Year Prior: \"",
              "        & FORMAT( _Target, \"#,##0\" )",
              "        & _Color",
              "        & FORMAT(",
              "            _Perc,",
              "            \" #,##0.0%; #,##0.0%; #,##0%\"",
              "        )",
              "        & \" )\""
            ],
            "isHidden": true,
            "lineageTag": "faf3bed7-a8d6-42b2-b0e4-edc35cd41bed"
          },
          {
            "name": "% Claims Approved",
            "displayFolder": "KPI Doughnut",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _ApprovedClaims =",
              "    CALCULATE(",
              "        [Sum],",
              "        'Table'[Boolean Dimension] = \"Approved\"",
              "    )",
              "VAR _Perc = DIVIDE( _ApprovedClaims, [Sum] )",
              "RETURN",
              "    FORMAT( _Perc, \"#,##0%\" )"
            ],
            "isHidden": true,
            "lineageTag": "e8761060-f832-42a7-8816-f806e256b7bd"
          },
          {
            "name": "# Claims Approved",
            "displayFolder": "KPI Bar",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _ApprovedClaims =",
              "    CALCULATE(",
              "        [Sum],",
              "        'Table'[Boolean Dimension] = \"Approved\"",
              "    )",
              "RETURN",
              "    FORMAT( _ApprovedClaims, \"#,##0,.0K\" )"
            ],
            "isHidden": true,
            "lineageTag": "1778fef3-fdfe-49f2-806a-74e0ca8b7fc8"
          },
          {
            "name": "KPI Bullet Subtitle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Increase = UNICHAR( 8599 )",
              "VAR _Decrease = UNICHAR( 8600 )",
              "VAR _Delta = [Sum (Δ PY YTD)]",
              "VAR _Arrow =",
              "    IF( _Delta > 0, _Increase, _Decrease )",
              "VAR _Result =",
              "    _Arrow & \" \"",
              "        & FORMAT( [Sum (Δ% PY YTD)], \"#,##0%\" )",
              "        & \" vs. LY\"",
              "RETURN",
              "    _Result"
            ],
            "isHidden": true,
            "lineageTag": "01eae849-d1a7-49ec-9afd-af6363015ed4"
          },
          {
            "name": "KPI Bullet Title",
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Goblins =",
              "    CALCULATE(",
              "        [Sum],",
              "        'Table'[Boolean Dimension] = \"Approved\"",
              "    )",
              "RETURN",
              "    FORMAT( _Goblins, \"#,##0,.0K\" )",
              "        & \" Approved Claims\""
            ],
            "isHidden": true,
            "lineageTag": "72cf28a2-c0bd-4d61-9e8e-591de15c40f4"
          },
          {
            "name": "Sum (Latest Data Point)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI Trend",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE(",
              "        MAX( 'Table'[Month] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR _LatestMonth = MONTH( _LatestDate )",
              "VAR _LatestYear = YEAR( _LatestDate )",
              "RETURN",
              "    CALCULATE(",
              "        [Sum],",
              "        'Date'[Month (MM)] = _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )"
            ],
            "isHidden": true,
            "lineageTag": "421c52e3-3109-4681-a6e4-b4c41c09908d"
          },
          {
            "name": "KPI Trend Line Title",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "FORMAT(",
              "    [Sum (Latest Data Point)],",
              "    \"#,##0,.0K\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "5a737d28-fd3a-4785-bdcd-52e8904a178a"
          },
          {
            "name": "KPI Trend Line Subtitle",
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE(",
              "        MIN( 'Table'[Month] ),",
              "        VALUES( 'Date'[Year (YYYY)] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR _LatestMonth = MONTH( _LatestDate )",
              "VAR _LatestYear = YEAR( _LatestDate )",
              "VAR _Start =",
              "    CALCULATE(",
              "        [Sum],",
              "        'Date'[Month (MM)] = _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )",
              "VAR _Finish = [Sum (Latest Data Point)]",
              "VAR _Increase = UNICHAR( 8599 )",
              "VAR _Decrease = UNICHAR( 8600 )",
              "VAR _Delta = _Finish - _Start",
              "VAR _Arrow =",
              "    IF(",
              "        _Delta > 0,",
              "        _Increase & \" Trending up\",",
              "        _Decrease & \" Trending down\"",
              "    )",
              "RETURN",
              "    _Arrow"
            ],
            "isHidden": true,
            "lineageTag": "cf8326ce-38a8-4c1f-91b8-fdd8f9b89b39"
          },
          {
            "name": "KPI Trend Conditional Formatting",
            "displayFolder": "Control Colours",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE(",
              "        MIN( 'Table'[Month] ),",
              "        VALUES( 'Date'[Year (YYYY)] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR _LatestMonth = MONTH( _LatestDate )",
              "VAR _LatestYear = YEAR( _LatestDate )",
              "VAR _Start =",
              "    CALCULATE(",
              "        [Sum],",
              "        'Date'[Month (MM)] = _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )",
              "VAR _Finish = [Sum (Latest Data Point)]",
              "VAR _Increase = UNICHAR( 8599 )",
              "VAR _Decrease = UNICHAR( 8600 )",
              "VAR _Delta = _Finish - _Start",
              "VAR _Arrow =",
              "    IF( _Delta > 0, \"#74afcc\", \"#c56161\" )",
              "RETURN",
              "    _Arrow"
            ],
            "isHidden": true,
            "lineageTag": "e17710f3-dd05-4d60-ab0d-2faa2d3f6a19"
          },
          {
            "name": "Sum (All Except Latest Point)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI Trend",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE(",
              "        MAX( 'Table'[Month] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR _LatestMonth = MONTH( _LatestDate )",
              "VAR _LatestYear = YEAR( _LatestDate )",
              "RETURN",
              "    CALCULATE(",
              "        [Sum],",
              "        'Date'[Month (MM)] <> _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )"
            ],
            "isHidden": true,
            "lineageTag": "c9e25d30-0f33-45d0-9b4c-9b0318ce13de"
          },
          {
            "name": "KPI Trend Comparison Subtitle",
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE(",
              "        MAX( 'Table'[Month] ),",
              "        VALUES( 'Date'[Year (YYYY)] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR _LatestMonth = MONTH( _LatestDate )",
              "VAR _LatestYear = YEAR( _LatestDate )",
              "VAR _Start =",
              "    CALCULATE(",
              "        [Sum (PY)],",
              "        'Date'[Month (MM)] = _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )",
              "VAR _Finish = [Sum (Latest Data Point)]",
              "VAR _Increase = UNICHAR( 9650 )",
              "VAR _Decrease = UNICHAR( 9660 )",
              "VAR _Delta = _Finish - _Start",
              "VAR _Arrow =",
              "    IF(",
              "        _Delta > 0,",
              "        _Increase & \" Higher than last year\",",
              "        _Decrease & \" Lower than last year\"",
              "    )",
              "RETURN",
              "    _Arrow"
            ],
            "isHidden": true,
            "lineageTag": "05fa42ff-6662-4b17-a9ac-7ebb19000a65"
          },
          {
            "name": "KPI Trend Comparison Conditional Formatting",
            "displayFolder": "Control Colours",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE(",
              "        MAX( 'Table'[Month] ),",
              "        VALUES( 'Date'[Year (YYYY)] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "VAR _LatestMonth = MONTH( _LatestDate )",
              "VAR _LatestYear = YEAR( _LatestDate )",
              "VAR _Start =",
              "    CALCULATE(",
              "        [Sum (PY)],",
              "        'Date'[Month (MM)] = _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )",
              "VAR _Finish = [Sum (Latest Data Point)]",
              "VAR _Increase = UNICHAR( 9650 )",
              "VAR _Decrease = UNICHAR( 9660 )",
              "VAR _Delta = _Finish - _Start",
              "VAR _Arrow =",
              "    IF( _Delta > 0, \"#74afcc\", \"#c56161\" )",
              "RETURN",
              "    _Arrow"
            ],
            "isHidden": true,
            "lineageTag": "572d9a0b-6fba-4154-b6b0-a073e99ec6eb"
          },
          {
            "name": "KPI Sparkline Trend Up/Down",
            "displayFolder": "Dynamic Titles",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "",
              "VAR _LatestDate =",
              "    CALCULATE (",
              "        MIN ( 'Table'[Month] ),",
              "        VALUES ( 'Date'[Year (YYYY)] ),",
              "        REMOVEFILTERS ( )",
              "    )",
              "VAR _LatestMonth = MONTH ( _LatestDate )",
              "VAR _LatestYear = YEAR ( _LatestDate )",
              "VAR _Start =",
              "    CALCULATE (",
              "        [Sum],",
              "        'Date'[Month (MM)] = _LatestMonth,",
              "        'Date'[Year (YYYY)] = _LatestYear",
              "    )",
              "VAR _Finish = [Sum (Latest Data Point)]",
              "VAR _Increase = UNICHAR ( 8599 )",
              "VAR _Decrease = UNICHAR ( 8600 )",
              "VAR _Delta = _Finish - _Start",
              "VAR _Arrow =",
              "    IF ( _Delta > 0, _Increase, _Decrease )",
              "RETURN",
              "    _Arrow"
            ],
            "isHidden": true,
            "lineageTag": "5d85f1a7-96b2-4a9f-a873-143edcd54282"
          },
          {
            "name": "Gauge %",
            "displayFolder": "KPI Gauge",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Goblins =",
              "    CALCULATE(",
              "        [Sum],",
              "        'Table'[Boolean Dimension] = \"Approved\"",
              "    )",
              "VAR _Perc = DIVIDE( _Goblins, [Sum] )",
              "RETURN",
              "    _Perc"
            ],
            "formatString": "0%;-0%;0%",
            "isHidden": true,
            "lineageTag": "c70eae56-3b9c-4b78-8306-110a1a9c49e2"
          },
          {
            "name": "Issues or No Issues",
            "displayFolder": "Boolean Conditional Text",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Count = [Count]",
              "VAR _Symbol =",
              "    SWITCH(",
              "        TRUE( ),",
              "        _Count > 0, UNICHAR( 10008 ),",
              "        _Count = 0, UNICHAR( 10004 ),",
              "        BLANK( )",
              "    )",
              "RETURN",
              "    _Symbol"
            ],
            "isHidden": true,
            "lineageTag": "0075047b-501d-420f-91c0-6c4974a9ff2f"
          },
          {
            "name": "# Issues (Text)",
            "displayFolder": "Repeated Text",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "REPT( UNICHAR( 10008 ), [Count] )"
            ],
            "isHidden": true,
            "lineageTag": "b8c93b14-6f6e-44f4-92a4-208bca84475b"
          }
        ],
        "partitions": [
          {
            "name": "2. Report-Specific Objects",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ 1 }"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "1. Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "724d8a875a79418db6f9113a2cf5d8eb"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18e219e8-e8e5-4a4e-8c86-825ff8a663c7",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4bd4c7d3-ed8c-4fc9-802b-4eb3b0893f5d",
        "measures": [
          {
            "name": "Percentage",
            "displayFolder": "Percent",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Total =",
              "    CALCULATE(",
              "        SUM( 'Table'[Quantitative] ),",
              "        REMOVEFILTERS( )",
              "    )",
              "RETURN",
              "    DIVIDE(",
              "        SUM( 'Table'[Quantitative] ),",
              "        _Total",
              "    )",
              "        + 0.15"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "ccbbf42b-88e3-4b49-8192-f592b6d02dc4"
          },
          {
            "name": "Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Sum",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "SUM( 'Table'[Quantitative] )"
            ],
            "formatString": "  #,##0",
            "lineageTag": "71445de7-2cd6-43b8-81cb-8b9dd1159740"
          },
          {
            "name": "Sum (CY YTD)",
            "displayFolder": "Sum\\YTD",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "CALCULATE(",
              "    [Sum],",
              "    CALCULATETABLE(",
              "        DATESYTD( 'Date'[Date] ),",
              "        'Date'[DatesWithSales (True/False)]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "202a6bc8-71c3-41cc-9349-cde551b031a0"
          },
          {
            "name": "Sum (PY)",
            "displayFolder": "Sum",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "CALCULATE(",
              "    [Sum],",
              "    SAMEPERIODLASTYEAR( 'Date'[Date] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6fe52e9a-2944-457b-97e7-ee4aadcdc2cc"
          },
          {
            "name": "Sum (Δ PY YTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Sum\\YTD\\vs. PY",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _CY = [Sum (CY YTD)]",
              "VAR _PY = [Sum (PY YTD)]",
              "VAR _Delta = _CY - _PY",
              "RETURN",
              "    _Delta"
            ],
            "formatString": "+#,##0;-#,##0;#,##0",
            "lineageTag": "4cb18752-6c6d-444e-b2dd-dff2e86ce817"
          },
          {
            "name": "Sum (Δ% PY YTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Sum\\YTD\\vs. PY",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "DIVIDE(",
              "    [Sum (Δ PY YTD)],",
              "    [Sum (PY)]",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "VAR _UpArrow = UNICHAR( 8595 )",
                "VAR _DownArrow = UNICHAR( 8593 )",
                "RETURN",
                "    _DownArrow & \" #,##0.0%\" & \";\"",
                "        &    // Negative numbers",
                "        _UpArrow",
                "        & \" #,##0.0%\"",
                "        & \";\"",
                "        &      // Positive numbers",
                "        \"#,##0.0\"                           // Zero"
              ]
            },
            "lineageTag": "546753a4-f8e4-45be-92c8-3a0ccdc60f66"
          },
          {
            "name": "Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Count",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "COUNTROWS(",
              "    VALUES( 'Table'[Dimension] )",
              ")"
            ],
            "lineageTag": "4b4de92d-e3ee-4139-a985-1b450ff40060"
          },
          {
            "name": "Sum (PY YTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sum\\YTD",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "CALCULATE(",
              "    [Sum (PY)],",
              "    CALCULATETABLE(",
              "        DATESYTD( 'Date'[Date] ),",
              "        'Date'[DatesWithSales (True/False)]",
              "    )",
              ")"
            ],
            "lineageTag": "56036eba-a803-48bd-9ad7-2d0f2af882bc"
          },
          {
            "name": "Sum (% of PY YTD)",
            "displayFolder": "Sum\\YTD\\vs. PY",
            "expression": [
              "",
              "--Disclaimer: DAX in these templates doesn't follow best practices",
              "--            Don't use this DAX as-is; the templates are intended to be illustrative.",
              "",
              "VAR _Actuals = [Sum (CY YTD)]",
              "VAR _Target = [Sum (PY YTD)]",
              "VAR _Perc = DIVIDE( _Actuals, _Target )",
              "RETURN",
              "    _Perc"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "efdaa006-24a4-4a68-a810-343bf07e07ee"
          }
        ],
        "partitions": [
          {
            "name": "1. Measures",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{ 1 }"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "163d92fff6ed49ff9051b07d98c0444d"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "3. Calendar Date",
            "formatString": "YYYY/MM/DD",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "79acd4a7-177f-46ac-b3f5-bd96e78c9259",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year (YYYY)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "1. Year",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e06802b7-acbd-4c08-aef6-9e0a94266bbd",
            "sourceColumn": "[Year (YYYY)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Year (MMYYYY)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "2. Month",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ce8c040b-4b49-4b02-aade-3f61ce62b490",
            "sourceColumn": "[Month Year (MMYYYY)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month (MM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "2. Month",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "584fa0c0-68d8-464b-a6f9-d1e9016a4bdc",
            "sourceColumn": "[Month (MM)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month (MMM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "2. Month",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "81b7a0c8-099d-443f-87e9-eb904f328750",
            "sortByColumn": "Month (MM)",
            "sourceColumn": "[Month (MMM)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DatesWithSales (True/False)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "displayFolder": "4. Indicators",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2313f5c5-cfd7-4d66-a709-8f57cc2b8adf",
            "sourceColumn": "[DatesWithSales (True/False)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsThisYear (True/False)",
            "dataType": "boolean",
            "displayFolder": "4. Indicators",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3d5a6501-7143-47f8-9b21-163efaf9a014",
            "sourceColumn": "[IsThisYear (True/False)]",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "42924f7d-1875-49e1-abad-09dccdadd421",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _LatestDate = MAX ( 'Table'[Month] )",
                "RETURN",
                "    ADDCOLUMNS (",
                "        CALENDAR (",
                "            DATE ( 2022, 1, 1 ),",
                "            DATE ( 2023, 12, 31 )",
                "        ),",
                "        \"Year (YYYY)\", YEAR ( ''[Date] ),",
                "        \"Month Year (MMYYYY)\",",
                "            FORMAT ( ''[Date], \"MMYYYY\" ),",
                "        \"Month (MM)\", MONTH ( ''[Date] ),",
                "        \"Month (MMM)\", FORMAT ( ''[Date], \"MMM\" ),",
                "        \"DatesWithSales (True/False)\",",
                "            ''[Date] < _LatestDate,",
                "        \"IsThisYear (True/False)\",",
                "            YEAR ( ''[Date] ) = YEAR ( _LatestDate )",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}