{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.963.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Table\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "extendedProperties": [
      {
        "name": "TabularEditor_DeploymentMetadata",
        "type": "json",
        "value": {
          "ClientMachine": "DESKTOP-NV69I5J",
          "DeploymentMode": "SaveUI",
          "TabularEditorBuild": "3.9.0.2972",
          "Time": "2023-07-25T23:35:00.5333614+00:00",
          "User": "DESKTOP-NV69I5J\\Klonk-Temp"
        }
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6428db5-956a-46cf-8e0d-f78eb01375b5",
            "sourceColumn": "Dimension",
            "summarizeBy": "none"
          },
          {
            "name": "Quantitative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea479855-4c8e-45af-927c-60b87abbeb86",
            "sourceColumn": "Quantitative",
            "summarizeBy": "sum"
          },
          {
            "name": "Sub-Dimension",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f44d7b1-03be-4dc8-ad1c-32b4503fb996",
            "sourceColumn": "Sub-Dimension",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f94a7412-424a-4c12-9e19-6a928be50131",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "74c7dcbc-f534-4da1-9c59-174298c17e81",
        "partitions": [
          {
            "name": "Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs9PysnMK1bSUQrKTy9NBTEUFIwMjIyADCOlWB1kFeGZVYlFKXAlxkCGKZoSt8z0jJLUIhRjzNHU+ObnZaMYYgxW4F+UjN0ZFsjSWNxgaIisAJsLDFFswLAf4kDXnLJU7A4wNEVRgM0JRigqsLrBEkUJhiOglngk5qQBwykdu0uMMdRgcYwJhiKs7sFQheEkoKdiAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Dimension = _t, #\"Sub-Dimension\" = _t, Year = _t, Quantitative = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Quantitative\", Int64.Type}, {\"Year\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "2. Report-Specific Objects",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "21661cfde1db4d40be113778b97a84f2"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "05cd4f72-d741-444a-8849-796154a583d9",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "bc077534-c5b0-40dd-9fb4-4bad6abc2bd2",
        "measures": [
          {
            "name": "1 - Percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Stacked Percentages",
            "expression": "1 - [Percentage] ",
            "isHidden": true,
            "lineageTag": "a797f413-2545-4e12-a017-c9decafc3fa4"
          },
          {
            "name": "Zero",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "Misc",
            "expression": "0",
            "formatString": "\" \"",
            "isHidden": true,
            "lineageTag": "9c5e001d-acf5-4a94-8c79-b36b22eddff2"
          },
          {
            "name": "90% of Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": "0.9 * [Sum]",
            "isHidden": true,
            "lineageTag": "3dfd2c42-1784-48db-b00d-f2279171b90d"
          },
          {
            "name": "Transparent",
            "displayFolder": "Control Colours",
            "expression": "\"#00000000\"",
            "isHidden": true,
            "lineageTag": "7af08448-2e99-4e55-a505-8e431865c8dd"
          },
          {
            "name": "One",
            "displayFolder": "Misc",
            "expression": "1",
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "ac584242-db7d-4988-837c-5bd76985c46d"
          },
          {
            "name": "5% of Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": "0.05 * [Sum]",
            "isHidden": true,
            "lineageTag": "7bf36b78-b7d5-408b-860f-e141b73f3749"
          },
          {
            "name": "110% of Highest Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.1 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "5b18d1b8-9148-45f3-8893-a6f86d294363"
          },
          {
            "name": "Min One",
            "displayFolder": "Misc",
            "expression": "-1",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebff2474-2af1-4c1e-b138-c5f3c295c261"
          },
          {
            "name": "120% of Highest Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "372933e1-0e0e-457e-8349-6aaaaa5cb5d9"
          },
          {
            "name": "Sum (2022; Inverse)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "For Format Strings",
            "expression": "- [Sum (2022)]",
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "2ad4db16-6991-4157-8219-d80f6deb39ed"
          },
          {
            "name": "2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "For Legends",
            "expression": "[Sum (2022; Inverse)]",
            "formatString": "#,##0; #,##0; #,##0",
            "isHidden": true,
            "lineageTag": "bec9c999-6fec-47de-8f1f-6e2ae0cd4437"
          },
          {
            "name": "2023",
            "displayFolder": "For Legends",
            "expression": "[Sum (2023)]",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8bcf8528-5a56-46a4-8577-7c5cfa488766"
          },
          {
            "name": "Year Colour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Colours",
            "expression": "IF ( SELECTEDVALUE ( 'Table'[Year] ) = \"  2022\", \"#ece6da\", \"#737068\" )",
            "isHidden": true,
            "lineageTag": "7a633807-acfb-4667-bf5f-0f51cfe82c98"
          },
          {
            "name": "Bar Chart & Candlestick - Change (Lower)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "IF ( ",
              "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
              "    MIN ( [Sum (2022)], [Sum (2023)] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "42be94b5-2cf7-403f-b817-e793d939313a"
          },
          {
            "name": "Bar Chart & Candlestick - Change (Higher)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "IF ( ",
              "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",",
              "    MAX ( [Sum (2022)], [Sum (2023)] )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "06a8e96e-b86e-4795-ae87-d11205f3f7ee"
          },
          {
            "name": "Bar Chart & Candlestick - Bar Color",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )",
              "RETURN",
              "IF ( ",
              "    _Attribute = \"CHANGE\",",
              "    \"#00000000\",",
              "    IF (",
              "        _Attribute = \"2023\", \"#737068\",",
              "        \"#ece6da\"",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "2ac1fede-d563-4021-b19f-cb3ad7697b75"
          },
          {
            "name": "120% of Highest Sum by Year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    [Sum],",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Year] ),",
              "        [Sum]",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "72ea17f8-178e-48f7-a73d-2a0479fdd182"
          },
          {
            "name": "Bar Chart & Candlestick - Label Color",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "For Bar Chart & Candlestick",
            "expression": [
              "",
              "VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )",
              "RETURN",
              "IF ( ",
              "    _Attribute = \"CHANGE\",",
              "    IF ( [Sum (Δ% '22 - '23)] > 0, \"#1f84bb\", \"#ec8b69\" ), \"#00000000\" )"
            ],
            "isHidden": true,
            "lineageTag": "0442ff64-b4ae-4dd0-bab9-992d9e1ec8f5"
          },
          {
            "name": "120% of Highest Delta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Control Axis Ranges",
            "expression": [
              "",
              "1.2 ",
              "* ",
              "CALCULATE(",
              "    MAX( [Sum (2022)], [Sum (2023)] ),",
              "    TOPN(",
              "        1,",
              "        VALUES( 'Table'[Dimension] ),",
              "        MAX( [Sum (2022)], [Sum (2023)] )",
              "    )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e64df63d-9b51-4dea-b0c7-7cfd61781d41"
          },
          {
            "name": "Min 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Duplicated Measures for Formatting",
            "expression": "-2",
            "isHidden": true,
            "lineageTag": "8a4b18d3-f2cd-440b-a115-9c6339b8ae7a"
          },
          {
            "name": "Zero #3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Duplicated Measures for Formatting",
            "expression": "0",
            "isHidden": true,
            "lineageTag": "a4149ffb-966e-4875-a3a3-d540e6ece0e0"
          },
          {
            "name": "Goblins",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Goblins\", 0.75 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "159adc75-7072-42b0-93ca-599cd80e5992"
          },
          {
            "name": "Y-Axis (Progress III)",
            "displayFolder": "For Progress Bar III",
            "expression": [
              "",
              "VAR _Dimension = SELECTEDVALUE ( 'Table'[Dimension] ) ",
              "RETURN",
              "SWITCH(",
              "    _Dimension,",
              "    \"Halflings\", 0.95, ",
              "    \"Goblins\", 0.70,",
              "    \"Orcs\", 0.45,",
              "    \"Elves\", 0.20",
              "    ,0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3ae4415e-2da2-4c0a-9850-4dc0e09a9821"
          },
          {
            "name": "Yellow",
            "displayFolder": "For Progress Bar III",
            "expression": "0.25",
            "formatString": "0%;-0%;0%",
            "lineageTag": "7b2ecbaf-aa8b-439d-aeb4-dd5a256af54d"
          },
          {
            "name": "Orcs",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Goblins\", 0.5 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "c3bfd392-d6d1-4ed7-ba57-e90ec17dc9e8"
          },
          {
            "name": "Halflings",
            "displayFolder": "For Progress Bar III",
            "expression": "IF ( SELECTEDVALUE( 'Table'[Dimension] ) = \"Halflings\", 1 )",
            "formatString": "0%;-0%;0%",
            "lineageTag": "69d09b41-5a01-404b-b885-00bcb54f8111"
          }
        ],
        "partitions": [
          {
            "name": "2. Report-Specific Objects",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "1. Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "724d8a875a79418db6f9113a2cf5d8eb"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18e219e8-e8e5-4a4e-8c86-825ff8a663c7",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4bd4c7d3-ed8c-4fc9-802b-4eb3b0893f5d",
        "measures": [
          {
            "name": "Percentage",
            "expression": [
              "",
              "VAR _Total = CALCULATE( SUM ( 'Table'[Quantitative] ), REMOVEFILTERS ( ) )",
              "RETURN",
              "DIVIDE ( ",
              "    SUM ( 'Table'[Quantitative] ), ",
              "    _Total",
              ") + 0.15"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ccbbf42b-88e3-4b49-8192-f592b6d02dc4"
          },
          {
            "name": "Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "expression": "SUM ( 'Table'[Quantitative] )",
            "formatString": "  #,##0",
            "lineageTag": "71445de7-2cd6-43b8-81cb-8b9dd1159740"
          },
          {
            "name": "Sum (2023)",
            "expression": [
              "",
              "// This would normally be just the sum; where Sum (2022) would be using time intelligence or a similar method to calculate PY",
              "CALCULATE(",
              "    [Sum],",
              "    'Table'[Year] = \"  2023\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "202a6bc8-71c3-41cc-9349-cde551b031a0"
          },
          {
            "name": "Sum (2022)",
            "expression": [
              "",
              "// This would normally be calculated using time intelligence or a similar method to calculate PY",
              "CALCULATE(",
              "    [Sum],",
              "    'Table'[Year] = \"  2022\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6fe52e9a-2944-457b-97e7-ee4aadcdc2cc"
          },
          {
            "name": "Sum (Δ '22 - '23)",
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "VAR _Delta = _CY - _PY",
              "RETURN",
              "_Delta"
            ],
            "formatString": "0",
            "lineageTag": "4cb18752-6c6d-444e-b2dd-dff2e86ce817"
          },
          {
            "name": "Sum (Δ% '22 - '23)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE (",
              "    [Sum (Δ '22 - '23)],",
              "    [Sum (2022)]",
              ")"
            ],
            "formatString": "+#,##0.0%;-#,##0.0%;#,##0.0%",
            "lineageTag": "546753a4-f8e4-45be-92c8-3a0ccdc60f66"
          },
          {
            "name": "Dumbbell Candle Upper (Green)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY > _PY, _CY )"
            ],
            "lineageTag": "ddabfcbe-403f-4e32-bb5c-9c775387f4fe"
          },
          {
            "name": "Dumbbell Candle Lower (Green)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY > _PY, _PY )"
            ],
            "lineageTag": "efacd5f7-169e-4e7d-b4fd-746f35c92480"
          },
          {
            "name": "Dumbbell Candle Upper (Red)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY < _PY, _PY )"
            ],
            "lineageTag": "d636fe70-992e-4e3b-a007-3613a2b538a8"
          },
          {
            "name": "Dumbbell Candle Lower (Red)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CY = [Sum (2023)]",
              "VAR _PY = [Sum (2022)]",
              "RETURN",
              "IF ( _CY < _PY, _CY )"
            ],
            "lineageTag": "38f51b3a-e517-4ced-8582-2c1941fc8caf"
          },
          {
            "name": "Average",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE( 'Table'[Quantitative] )",
            "lineageTag": "9e1730ae-9fa7-4e42-ab67-b1258eff1fa6"
          }
        ],
        "partitions": [
          {
            "name": "1. Measures",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "3. Report-Specific Calculation Group",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "2023",
              "expression": "[Sum (2023)]",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING ()"
              },
              "ordinal": 1
            },
            {
              "name": "2022",
              "expression": "[Sum (2022)]",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING ()"
              },
              "ordinal": 0
            },
            {
              "name": "CHANGE",
              "expression": [
                "",
                "MAX ( [Sum (2022)], [Sum (2023)] )",
                ""
              ],
              "formatStringDefinition": {
                "expression": "[Sum (Δ% '22 - '23)]"
              },
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "46153ef3-7f1e-4409-9fd9-da8badcc1c16",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "eb4d2363-14da-44a2-b9e8-6a6b70069eea",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "e8e227b7-fd27-4a64-87a2-95da79648028",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "3. Report-Specific Disconnected Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "803854adc3014b728952e70307c7162a"
          }
        ],
        "columns": [
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b683d841-5ca8-40dc-a3aa-b94c9aa78716",
            "sortByColumn": "Order",
            "sourceColumn": "[Attribute]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "781445e6-72e9-47cf-ae90-7148209c7c40",
            "sourceColumn": "[Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "fe2cdcff-7270-464b-bddc-7b06cdc7fdc3",
        "measures": [
          {
            "name": "Bar Chart & Candlestick",
            "expression": [
              "",
              "// sqlbi measure replacement method",
              "CALCULATE( ",
              "    [Zero],",
              "    TREATAS(",
              "        DISTINCT( '3. Report-Specific Disconnected Table'[Attribute] ),",
              "        '3. Report-Specific Calculation Group'[Attribute]",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "IF ( \r",
                "    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = \"CHANGE\",\r",
                "    FORMAT( [Sum (Δ% '22 - '23)], \"+0\\.0%;-0\\.0%;0\\.0%\"),\r",
                "    \"#,##0\"\r",
                ")"
              ]
            },
            "isHidden": true,
            "lineageTag": "0e596993-63a5-42a9-9dc0-aa320666263d"
          }
        ],
        "partitions": [
          {
            "name": "3. Report-Specific Disconnected Table",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SELECTCOLUMNS( ",
                "    '3. Report-Specific Calculation Group',",
                "    \"Attribute\", '3. Report-Specific Calculation Group'[Attribute],",
                "    \"Order\", '3. Report-Specific Calculation Group'[Ordinal] ",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "4. Report-Specific SVG Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4f5be44a59594685aa453dcbf609e978"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ea94bcb1-fc74-4dcb-bb99-815fc2be8ccb",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f4ab3a84-bd81-4db3-82e0-074ee7960e80",
        "measures": [
          {
            "name": "Card with Columns and Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "/* SETUP */",
              "VAR _spaceBetweenColumns = 5.5 // Space that will be reserved between columns",
              "VAR _maxSizeOfColumn = 3.5 // Max size of column, if the calculated value is bigger than this, the column will be this size",
              "VAR _columnRounding = 5 // Rounding of column corners",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 250 // Height size of the SVG",
              "VAR _initialTbl = // ADD YOUR TABLE, PERIOD COLUMN (DATE, MONTH, QUARTER, YEAR,...) + MEASURE HERE",
              "    ADDCOLUMNS (",
              "        SELECTCOLUMNS(SUMMARIZE ( 'Table', 'Table'[Quantitative] ), \"@xAxisPeriod\", [Quantitative] ),",
              "        \"@val\", [Sum]",
              "    )",
              "VAR _target = [Average] // Target value or measure",
              "",
              "/* TEXT DECLARTIONS */",
              "VAR _firstLineInitialText = \"Total target is on\"",
              "VAR _firstLineEndText =  \"~ missing\"",
              "VAR _secondLineInitialText = \"Period target is on\"",
              "VAR _secondLineEndText =  \"~ sold\"",
              "VAR _thirdLineMiddleText = \"of\"",
              "VAR _thirdLineEndText =  \"months were successful\"",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _grey = \"#E6E6E6\" // Will be used for all other columns",
              "VAR _activePartsColor = \"#658E95\" // Will be used for all highly colored parts of card",
              "VAR _darkGrey = \"#808080\" // Will be used for all text",
              "VAR _targetLineColor = \"#A8A8A8\" // Will be used for target line",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' width='\"&_width&\"' height='\"&_height&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CSS DECLARATIONS */",
              "VAR _style = ",
              "\"<style>",
              "    text{",
              "        font-family:Segoe UI;",
              "    }",
              "    .columns{",
              "         opacity: 1;",
              "         outline: none;",
              "    }",
              "    .line{",
              "        stroke:\"&_targetLineColor&\"; ",
              "        stroke-width:1.25;",
              "        stroke-dasharray:5 5;",
              "    }",
              "    .txtGroup{",
              "        dominant-baseline: middle;",
              "        text-anchor:start;",
              "    }",
              "    .bolder{",
              "        font-weight: bold;",
              "    }",
              "</style>\"",
              "",
              "/* CALCULATION */",
              "VAR _preparedTbl = ",
              "    ADDCOLUMNS (",
              "        _initialTbl,",
              "        \"@rowNum\", ROWNUMBER (_initialTbl, ORDERBY ( [@xAxisPeriod], ASC ) )",
              "    )",
              "VAR _maxValue =",
              "    MAXX ( _preparedTbl, [@val] )",
              "VAR _rowCounter =",
              "    COUNTROWS ( _preparedTbl )",
              "VAR _modifiedValue = _rowCounter*_target",
              "VAR _resultSizeOfColumns =",
              "    VAR _cal =",
              "        ROUND ( DIVIDE ( 100 - ( ( _rowCounter + 1 ) * _spaceBetweenColumns ), _rowCounter ), 1 )",
              "    RETURN",
              "        IF ( _cal > _maxSizeOfColumn, _maxSizeOfColumn, _cal )",
              "VAR _columns =",
              "    CONCATENATEX (",
              "        _preparedTbl,",
              "        VAR _colorOfColumn =",
              "            IF(_target<[@val],_activePartsColor,_grey) // Rules for coloring columns",
              "        VAR _startOfColumn =",
              "            ROUND ( DIVIDE ( [@val], _maxValue ) * 40, 1 )",
              "        VAR _positionCounter = ( ( [@rowNum] - 1 ) * _resultSizeOfColumns ) + ( _spaceBetweenColumns * [@rowNum] )",
              "        RETURN",
              "            \"<rect class='columns' x='\" & _positionCounter & \"%' y='\" & 85-_startOfColumn & \"%' width='\" & _resultSizeOfColumns & \"%' height='\" & _startOfColumn & \"%' fill='\" & _colorOfColumn & \"' rx='\"&_columnRounding&\"' />\"",
              "    )",
              "VAR _targetLine =",
              "    VAR _y = 85-ROUND ( DIVIDE ( _target, _maxValue ) * 40, 1 )",
              "    RETURN",
              "    \"<line class='line' x1='\"&_spaceBetweenColumns&\"%' x2='\"&100-_spaceBetweenColumns&\"%' y1='\"&_y&\"%' y2='\"&_y&\"%' />\"",
              "VAR _initialText =",
              "\"<g class='txtGroup'>\"&",
              "    \"<text y='4%' x='2.5%' font-size='107.5%' fill='\"&_darkGrey&\"'><tspan class='bolder'> \"&_firstLineInitialText&\" <tspan fill='\"&_activePartsColor&\"'>\"",
              "        &FORMAT(ROUND(DIVIDE(SUMX(_preparedTbl,[@val]),_modifiedValue),2),\"0%\")& ",
              "        \"</tspan></tspan><tspan font-size='80%'> \"&_firstLineEndText&\" \"&_modifiedValue-SUMX(_preparedTbl,[@val])&\" </tspan>",
              "    </text>\"",
              "    &",
              "    \"<text y='16.5%' x='2.5%' fill='\"&_darkGrey&\"'>",
              "        \"&_secondLineInitialText&\" <tspan fill='\"&_activePartsColor&\"' class='bolder'>\"",
              "        &FORMAT(ROUND(DIVIDE(SUMX(_preparedTbl,[@val]),_modifiedValue),2),\"0%\")& ",
              "        \"</tspan> <tspan font-size='80%'> \"&_secondLineEndText&\" \"&SUMX(_preparedTbl,[@val])&\" </tspan>",
              "    </text>\"",
              "    &",
              "    \"<text y='29%' x='2.5%' fill='\"&_darkGrey&\"'>",
              "        <tspan fill='\"&_activePartsColor&\"' class='bolder'>\"",
              "        & COUNTROWS(FILTER(_preparedTbl,[@val]>=_target)) & ",
              "        \"</tspan> \"&_thirdLineMiddleText&\"",
              "        <tspan class='bolder'>\"",
              "        & _rowCounter & ",
              "        \"</tspan> \"&_thirdLineEndText&\"",
              "    </text>",
              "</g>\"",
              "VAR SVGImageURL = _svgDeclaration & _svgHeader & _style & _initialText & _targetLine &  _columns  & _svgEnd",
              "RETURN",
              "    SVGImageURL"
            ],
            "lineageTag": "6a23f99d-c620-4dff-8827-4e4ba637002a"
          },
          {
            "name": "Card with Donut progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "/* SETUP */",
              "VAR _total = [Sum (2022)]  // Will be used as a target",
              "VAR _value = [Sum (2023)] // Will be used as a current value",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "VAR _CanvasSize = MIN(_height,_width) // Canvas size",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "",
              "/* PRE CALCULATION */",
              "VAR _halfSize = _CanvasSize/2 // Half of the canvas size",
              "VAR _r = _halfSize-_paddning*1.5 // Radius of the circle",
              "VAR _round = 2*PI()*_r",
              "VAR _perc = _value/_total // Percentage of the current value",
              "VAR _ratio = _round-_round*_perc // Ratio of the current value",
              "VAR _clr =  // Determine the color of the circle based on the percentage",
              "    SWITCH(TRUE(),",
              "        _perc>=0.75,_positive, // Positive Color",
              "        _perc>=0.5,_neutral, // Neutral Color",
              "        _negative // Negative Color",
              "    )",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _styles = ",
              "\"",
              "  <style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              "    .backgroundCircle{",
              "      transform:rotate(-90deg) translate(-\"&(_height+_width)/2&\"px, \"&(_width-_height)/2&\"px);",
              "    }",
              "    .backgroundCircle{",
              "      fill: transparent;",
              "      stroke-width: \"&_paddning&\";",
              "    }",
              "    .background{",
              "      stroke: #e0e0e0;",
              "    }",
              "    .filling{",
              "      stroke: \"&_clr&\";",
              "      stroke-linecap: round;",
              "      stroke-dasharray: \"&_round&\";",
              "      stroke-dashoffset: \"&_ratio&\";",
              "    }",
              "    .mainText{",
              "      fill: \"&_clr&\";",
              "      font-size: 225%;",
              "      text-anchor: middle;",
              "      dominant-baseline: middle;",
              "      font-weight: bold;",
              "    }",
              "    .subTexts{",
              "      fill: #CCCCCC;",
              "      font-size: 95%;",
              "      dominant-baseline: middle;",
              "    }",
              "    .leftPositioned{",
              "        text-anchor: end;",
              "    }",
              "    .rightPositioned{",
              "        text-anchor: start;",
              "    }",
              "    .bolden{",
              "        font-weight: bold;",
              "    }",
              "  </style>",
              "\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\" & _height & \"' width='\" & _width & \"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _sv =",
              "\"",
              "  <g class='backgroundCircle'>",
              "  <circle r='\"&_r&\"' cx='50%' cy='50%' class='background' />",
              "  <circle r='\"&_r&\"' cx='50%' cy='50%' class='filling'/>",
              "  </g>",
              "  <g class='mainText'>",
              "  <text x='50%' y='37.5%' >\"&FORMAT(_perc,\"0.0%\")&\"</text>",
              "  </g>",
              "  <g class='subTexts'>",
              "  <g class='leftPositioned'>",
              "  <text x='51%' y='50.5%' >\"&\"Target:\"&\"</text>",
              "  <text x='51%' y='60%' >\"&\"Current:\"&\"</text>",
              "  <text x='51%' y='69.5%' class='bolden'>\"&\"Missing:\"&\"</text>",
              "  </g>",
              "  <g class='rightPositioned'>",
              "  <text x='53%' y='50.5%' >\"&_total&\"</text>",
              "  <text x='53%' y='60%' >\"&ROUND(_value,1)&\"</text>",
              "  <text x='53%' y='69.5%' class='bolden'>\"&ROUND(_total-_value,1)&\"</text>",
              "  </g>",
              "  </g>",
              "\"",
              "VAR _result = _svgDeclaration & _svgHeader & _styles & _sv & _svgEnd ",
              "RETURN",
              "   _result"
            ],
            "lineageTag": "9f7ba69f-7cec-4a41-a562-10e51f9ac0a2"
          },
          {
            "name": "Text Card ShowCase One",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _actualQuantity = [Sum (2023)] // Get the actual quantity from the context (Usually it would be measure for the actual year)",
              "VAR _previousQuantity = [Sum (2022)] // Get the previous quantity from the context (Usually it would be measure for the previous year)",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    font-size:85%;",
              "    fill:#BBB;",
              "}",
              ".bolder{",
              "    font-weight:bold;",
              "    fill:#808080;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _div = DIVIDE(_actualQuantity,_previousQuantity)-1",
              "VAR _colorForPercentage = ",
              "    SWITCH(TRUE(),",
              "        _div>0,_positive,",
              "        _div<0,_negative,",
              "        _neutral",
              "    )",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText'>",
              "        <text y='10%'>",
              "            In year \"&_yearDefinition&\" were <tspan class='bolder'>\"& _actualQuantity &\"</tspan> members of individual races.",
              "        </text>",
              "        <text y='22.5%'>",
              "            It is about <tspan class='bolder'>\"& FORMAT(_actualQuantity-_previousQuantity,\"+# more;-# less\") &\" <tspan font-size='85%' fill='\"&_colorForPercentage&\"'>( \"&FORMAT(_div,\"+0.0%;-0.0%\")&\")</tspan></tspan> then previous year.",
              "        </text>",
              "    </g>\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _content & _svgEnding"
            ],
            "lineageTag": "c2f6787a-34a5-42fc-99a8-da203f868e63"
          },
          {
            "name": "Text Card ShowCase Two",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _tableInitiator =",
              "CALCULATETABLE(",
              "    ADDCOLUMNS(",
              "        VALUES('Table'[Dimension]),",
              "        \"@counter\", [Sum]",
              "    ),",
              "    KEEPFILTERS('Table'[Year] = _yearDefinition)",
              ")",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    font-size:85%;",
              "    fill:#BBB;",
              "}",
              ".bolder{",
              "    font-weight:bold;",
              "    fill:#808080;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _counter = COUNTROWS(_tableInitiator)",
              "VAR _topRow = INDEX(1,_tableInitiator,ORDERBY([@counter],DESC))",
              "VAR _topRace = SELECTCOLUMNS(_topRow,[Dimension])",
              "VAR _topRaceMembers = SELECTCOLUMNS(_topRow,[@counter])",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText'>",
              "        <text y='10%'>",
              "            In evidence are <tspan class='bolder'>\"& _counter &\"</tspan> races.",
              "        </text>",
              "        <text y='22.5%'>",
              "            Largest race currently are <tspan class='bolder'>\"& _topRace &\"</tspan> with <tspan class='bolder'>\"&_topRaceMembers&\"</tspan> members.",
              "        </text>",
              "    </g>\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _content & _svgEnding"
            ],
            "lineageTag": "f1b5120b-0bad-4f65-9a59-49b37d2d3a28"
          },
          {
            "name": "Text Card ShowCase Three",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _yearDefinition = MAX('Table'[Year]) // Get the year from the context",
              "VAR _tableInitiator =",
              "CALCULATETABLE(",
              "    ADDCOLUMNS(",
              "        VALUES('Table'[Sub-Dimension]),",
              "        \"@counter\", [Sum]",
              "    ),",
              "    KEEPFILTERS('Table'[Year] = _yearDefinition && 'Table'[Dimension] = \"Elves\")",
              ")",
              "",
              "/* STYLE DECLARTIONS */",
              "VAR _style = // This is the style of the card, here you can define the style",
              "\"<style>",
              "    text{",
              "        font-family: Segoe UI;",
              "    }",
              ".mainText{",
              "    font-size:85%;",
              "    fill:#BBB;",
              "}",
              ".bolder{",
              "    font-weight:bold;",
              "    fill:#808080;",
              "}",
              ".smallerItalic{",
              "    font-size:85%;",
              "    font-style: italic;",
              "}",
              "</style>\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _header = \"data:image/svg+xml;utf8,\"",
              "VAR _svgDeclaration = \"<svg xmlns='http://www.w3.org/2000/svg'>\"",
              "VAR _svgEnding = \"</svg>\"",
              "",
              "/* CALCULATION */",
              "VAR _counter = COUNTROWS(_tableInitiator)",
              "VAR _topRow = INDEX(1,_tableInitiator,ORDERBY([@counter],DESC))",
              "VAR _topRace = SELECTCOLUMNS(_topRow,[Sub-Dimension])",
              "VAR _topRaceMembers = SELECTCOLUMNS(_topRow,[@counter])",
              "VAR _content =  // This is the content of the card, here you can define the text",
              "    \"<g class='mainText'>",
              "        <text y='10%'>",
              "            They work in <tspan class='bolder'>\"& _counter &\"</tspan> professions",
              "        </text>",
              "        <text y='22.5%'>",
              "           and mostly they are <tspan class='bolder'>\"&_topRace&\"</tspan><tspan class='smallerItalic'> (\"&_topRaceMembers&\")</tspan>.",
              "        </text>",
              "    </g>\"",
              "",
              "RETURN",
              "_header & _svgDeclaration & _style & _content & _svgEnding"
            ],
            "lineageTag": "901fd391-ff5d-42ab-879b-6c87c8fbd39b"
          },
          {
            "name": "Slope KPI Chart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _tbl = ",
              "    ADDCOLUMNS(",
              "        ADDCOLUMNS(",
              "            SUMMARIZE('Table','Table'[Dimension]),",
              "            \"@vl\", [Sum (2023)],",
              "            \"@vlFive\", [Sum (2022)]),",
              "            \"@change\",[@vlFive]-[@vl]",
              "        )",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 250 // Height size of the SVG",
              "VAR _padding = 15",
              "VAR _ballsRadius = 5",
              "",
              "VAR _leftXCategory = \"2022\"",
              "VAR _rightXCategory = \"2023\"",
              "",
              "/* COLORS DECLARTIONS */",
              "VAR _green = \"#658E95\"",
              "VAR _red = \"#D64550\"",
              "VAR _grey = \"#EDEBE9\"",
              "VAR _lightGrey = \"#F0F0F0\"",
              "VAR _darkGrey = \"#CCCCCC\"",
              "",
              "/* SVG DECLARTIONS */",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "VAR _style = \"",
              "<style>",
              "text{",
              "    font-family: Segoe UI;",
              "}",
              ".greyText{",
              "     fill: \"&_darkGrey&\";",
              "}",
              ".middleText{",
              "    text-anchor: middle; ",
              "    font-size: 10;",
              "}",
              ".linedText{",
              "    dominant-baseline: middle; ",
              "    font-size: 10;",
              "}",
              ".bolder{",
              "    font-weight: bold;",
              "} ",
              ".baseLines{",
              "    stroke-width: 2;",
              "    stroke: \"&_lightGrey&\"; ",
              "    stroke-dasharray: 5,5;",
              "}",
              ".lineStroke{",
              "    stroke-width: 3;",
              "}",
              "</style>\"",
              "",
              "/* CALCULATION */",
              "VAR _doublePadding = _padding*2",
              "VAR _halfPadding = _padding/2",
              "VAR _usableHeight = _height-_doublePadding*2",
              "VAR _textYPostion = _usableHeight+_doublePadding",
              "VAR _betweenLineSpacer = _doublePadding*3",
              "VAR _topRow = INDEX(1, _tbl, ORDERBY(MAX([@vl],[@vlFive]),DESC))",
              "VAR _bottomRow = INDEX(1, _tbl, ORDERBY(MAX([@vl],[@vlFive]),ASC))",
              "VAR _maxValue = MAXX(_topRow,MAX([@vl],[@vlFive]))",
              "VAR _maxx = _maxValue*1.1",
              "VAR _maxC = MAXX(_tbl,[@change])",
              "VAR _minValue = MINX(_bottomRow,MIN([@vl],[@vlFive]))",
              "VAR _minx = _minValue*0.6",
              "VAR _minC = MINX(_tbl,[@change])",
              "VAR _diff = (_maxx-_minx)",
              "VAR _baseTexts =",
              "    VAR _topOfLine = (1-DIVIDE(_maxValue-_minx,_diff))*_usableHeight+_halfPadding",
              "    VAR _bottomOfLine = (1-DIVIDE(_minValue-_minx,_diff))*_usableHeight+_halfPadding",
              "    RETURN",
              "    \"<g class='middleText greyText'>",
              "        <text x='\"&_doublePadding&\"' y='\"&_textYPostion&\"'>\"&_leftXCategory&\"</text>",
              "        <text x='\"&_betweenLineSpacer&\"' y='\"&_textYPostion&\"'>\"&_rightXCategory&\"</text>",
              "    </g>",
              "    <g class='baseLines'>",
              "        <line x1='\"&_doublePadding&\"' x2='\"&_doublePadding&\"' y1='\"&_topOfLine&\"' y2='\"&_bottomOfLine&\"'/>",
              "        <line x1='\"&_betweenLineSpacer&\"' x2='\"&_betweenLineSpacer&\"' y1='\"&_topOfLine&\"' y2='\"&_bottomOfLine&\"'/>",
              "    </g>\"",
              "VAR _circles =",
              "    CONCATENATEX(FILTER(_tbl,NOT [@change] IN {_maxC,_minC}),",
              "        VAR _color = SWITCH([@change],_maxC,_green,_minC,_red,_grey)",
              "        VAR _yOne = (1-DIVIDE([@vl]-_minx,_diff))*_usableHeight+_halfPadding",
              "        VAR _yTwo = (1-DIVIDE([@vlFive]-_minx,_diff))*_usableHeight+_halfPadding",
              "        RETURN",
              "        \"<circle cx='\"&_doublePadding&\"' cy='\"&_yOne&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<circle cx='\"&_betweenLineSpacer&\"' cy='\"&_yTwo&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<line class='lineStroke' x1='\"&_doublePadding&\"' x2='\"&_betweenLineSpacer&\"' y1='\"&_yOne&\"' y2='\"&_yTwo&\"' stroke='\"&_color&\"'/>\"",
              "        & IF(_color<>_grey,",
              "        \"<text class='bolderLinedText' x='\"&_betweenLineSpacer+_padding&\"' y='\"&_yTwo&\"' fill='\"&_color&\"'>\"&[Dimension]&\"</text>\",\"\"))",
              "VAR _circlesUps =",
              "    CONCATENATEX(FILTER(_tbl, [@change] IN {_maxC,_minC}),",
              "        VAR _color = SWITCH([@change],_maxC,_green,_minC,_red,_grey)",
              "        VAR _div = DIVIDE([@vlFive],[@vl])-1",
              "        VAR _resultTexts = ",
              "            SWITCH(",
              "                [@change],",
              "                _maxC,\"increased by \",",
              "                _minC,\"decreased by \"",
              "            )&\"<tspan class='bolder' fill='\"&_color&\"'>\"&FORMAT(_div,\"0.0%;0.0%\")&\"</tspan>\"",
              "        VAR _yOne = (1-DIVIDE([@vl]-_minx,_diff))*_usableHeight+_halfPadding",
              "        VAR _yTwo = (1-DIVIDE([@vlFive]-_minx,_diff))*_usableHeight+_halfPadding",
              "        RETURN",
              "        \"<circle cx='\"&_doublePadding&\"' cy='\"&_yOne&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<circle cx='\"&_betweenLineSpacer&\"' cy='\"&_yTwo&\"' r='\"&_ballsRadius&\"' fill='\"&_color&\"'/>\"",
              "        &",
              "        \"<line class='lineStroke' x1='\"&_doublePadding&\"' x2='\"&_betweenLineSpacer&\"' y1='\"&_yOne&\"' y2='\"&_yTwo&\"' stroke='\"&_color&\"'/>\"",
              "        & IF(_color<>_grey,",
              "        \"<text class='linedText' x='\"&_betweenLineSpacer+_padding&\"' y='\"&IF([@change]=_maxC,\"45%\",\"55%\")&\"' fill='\"&_darkGrey&\"'><tspan class='bolder' fill='\"&_color&\"'>\"&[Dimension]&\"</tspan> \"&_resultTexts&\"</text>\",\"\"))",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _baseTexts &_circles & _circlesUps & _svgEnd",
              "RETURN",
              "   _result"
            ],
            "lineageTag": "1c55942f-0cf8-4a09-b92e-708b271da829"
          },
          {
            "name": "Progress Simple bar chart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _total = [Sum (2022)]  // Will be used as a target",
              "VAR _value = [Sum (2023)] // Will be used as a current value",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#242425\" // Darkgrey Color",
              "",
              "VAR _stateColor = IF(_total>_value,_negative,_positive)",
              "",
              "/* SVG DECLARTIONS */",
              "// BASIC SVG DECLARATION",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* STYLE DECLARATIONS */",
              "VAR _style = \"",
              "<style>",
              "text{",
              "    font-family: Segoe UI;",
              "    dominant-baseline: middle;",
              "    text-anchor: middle;",
              "}",
              ".progressBar{",
              "    fill: \"&_stateColor&\";",
              "}",
              ".endLine{",
              "    stroke: \"&_darkGrey&\";",
              "    stroke-width: 3;",
              "    stroke-linecap: round;",
              "    stroke-dasharray: 2.5 5;",
              "}",
              ".mainText{",
              "    fill: \"&_stateColor&\";",
              "    font-size: 125%;",
              "    font-weight: bold;",
              "}",
              ".supportText{",
              "    fill:#BBB;",
              "    font-size: 100%;",
              "}",
              "</style>\"",
              "",
              "/* CALCULATION */",
              "// INSERT YOUR CALCULATION HERE",
              "VAR _doublePadding = (_paddning*2)",
              "VAR _usableWidth= _width-(_doublePadding*2)",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _yStartPosition = _height*0.50",
              "VAR _yEndPosition = _usableHeight*0.25",
              "VAR _barWidth = IF(_total>=_value,DIVIDE(_value,_total)*_usableWidth,_usableWidth)",
              "VAR _linePosition = IF(_total>=_value,_width-_doublePadding,DIVIDE(_total,_value)*_usableWidth)",
              "VAR _bar = \"<rect class='progressBar' x='\"&_doublePadding&\"' y='\"&_yStartPosition&\"' width='\"&_barWidth&\"' height='\"&_yEndPosition&\"' rx='1.5%' />\"",
              "VAR _endLine = \"<line class='endLine' x1='\"&_linePosition&\"' x2='\"&_linePosition&\"' y1='\"&_yStartPosition*0.95&\"' y2='\"&(_yStartPosition+_yEndPosition)*1.05&\"' />\"",
              "VAR _texts = ",
              "    \"<text class='mainText' x='50%' y='\" &_yStartPosition*0.60&\"'>\"&FORMAT(DIVIDE(_value,_total),\"0.0%\")&\" ~ \"&IF((_value-_total)<0,\"Not filled\",\"Filled\")&\"</text>",
              "    <text class='supportText' x='50%' y='\" &_yStartPosition*0.825&\"'>Current: \"&_value&\" | Target: \"&_total&\"</text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _bar & _texts & _endLine & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "dc313c4a-8e08-46bf-a9a4-c430139a0ddf"
          },
          {
            "name": "Progress More Complex bar chart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "/* SETUP */",
              "VAR _total = [Sum (2022)]  // Will be used as a target",
              "VAR _value = [Sum (2023)] // Will be used as a current value",
              "",
              "// CANVAS SIZE",
              "VAR _width = 365 // Width size of the SVG",
              "VAR _height = 220 // Height size of the SVG",
              "",
              "// PADDING SETUP",
              "VAR _paddning = 15 // Padding between the circle and the canvas",
              "",
              "/* COLOR DEFINITION */",
              "VAR _positive = \"#658E95\" // Positive Color",
              "VAR _neutral = \"#E7E74E\" // Neutral Color",
              "VAR _negative = \"#7D1D3A\" // Negative Color",
              "VAR _darkGrey = \"#242425\" // Darkgrey Color",
              "",
              "VAR _stateColor = IF(_total>_value,_negative,_positive)",
              "",
              "/* SVG DECLARTIONS */",
              "// BASIC SVG DECLARATION",
              "VAR _svgDeclaration = \"data:image/svg+xml;utf8,\"",
              "VAR _svgHeader = \"<svg xmlns='http://www.w3.org/2000/svg' height='\"&_height&\"' width='\"&_width&\"'>\"",
              "VAR _svgEnd = \"</svg>\"",
              "",
              "/* STYLE DECLARATIONS */",
              "VAR _style = \"",
              "<style>",
              "text{",
              "    font-family: Segoe UI;",
              "    dominant-baseline: middle;",
              "    text-anchor: middle;",
              "}",
              ".progressBar{",
              "    fill: #CCC;",
              "}",
              ".endLine{",
              "    stroke: \"&_darkGrey&\";",
              "    stroke-width: 3;",
              "    stroke-linecap: round;",
              "    stroke-dasharray: 2.5 5;",
              "}",
              ".mainText{",
              "    fill: \"&_stateColor&\";",
              "    font-size: 125%;",
              "}",
              ".supportText{",
              "    fill:#BBB;",
              "    font-size: 100%;",
              "}",
              ".negativeResult{",
              "    fill: url(#negativePattern);",
              "    stroke: \"&_negative&\";",
              "    stroke-width: 1;",
              "    stroke-dasharray: 7 5;",
              "}",
              ".positiveResult{",
              "    fill: \"&_positive&\";",
              "    stroke: none;",
              "}",
              ".negPatternLines{",
              "    fill-opacity: 1;",
              "    stroke: \"&_negative&\";",
              "}",
              ".bolden{",
              "    font-weight: bold;",
              "}",
              "</style>\"",
              "",
              "/* DEFS + PATTERNS DECLARATIONS */",
              "VAR _defs =",
              "\"<defs>",
              "    <pattern id='negativePattern' x='0' y='0' width='10' height='10' patternUnits='userSpaceOnUse'>",
              "        <line class='negPatternLines' x1='10' x2='0' y1='0' y2='10' />",
              "    </pattern>",
              "</defs>\"",
              "",
              "/* CALCULATION */",
              "// INSERT YOUR CALCULATION HERE",
              "VAR _doublePadding = (_paddning*2)",
              "VAR _usableWidth= _width-(_doublePadding*2)",
              "VAR _usableHeight = _height-_doublePadding",
              "VAR _yStartPosition = _height*0.50",
              "VAR _yEndPosition = _usableHeight*0.25",
              "VAR _div = DIVIDE(_value,_total)",
              "VAR _divModifiedByWidth = _div*_usableWidth",
              "VAR _barWidth = IF(_total>=_value,_divModifiedByWidth,_usableWidth)",
              "VAR _linePosition = IF(_total>=_value,_width-_doublePadding,DIVIDE(_total,_value)*_usableWidth)",
              "VAR _bar = \"<rect class='progressBar' x='\"&_doublePadding&\"' y='\"&_yStartPosition&\"' width='\"&_barWidth&\"' height='\"&_yEndPosition&\"'/>\"",
              "& ",
              "    IF(_total>_value,",
              "        \"<rect class='negativeResult' x='\"&_doublePadding+_barWidth&\"' y='\"&_yStartPosition&\"' width='\"&_linePosition-(_doublePadding+_barWidth)&\"' height='\"&_yEndPosition&\"' />\",",
              "        \"<rect class='positiveResult' x='\"&_linePosition&\"' y='\"&_yStartPosition&\"' width='\"&_barWidth-_linePosition+_doublePadding&\"' height='\"&_yEndPosition&\"' />\"",
              "    )",
              "VAR _endLine = \"<line class='endLine' x1='\"&_linePosition&\"' x2='\"&_linePosition&\"' y1='\"&_yStartPosition*0.95&\"' y2='\"&(_yStartPosition+_yEndPosition)*1.05&\"' />\"",
              "VAR _texts = ",
              "    \"<text class='mainText bolden' x='50%' y='\" &_yStartPosition*0.60&\"'>\"&FORMAT(_div,\"0.0%\")&\" ~ \"&IF((_value-_total)<0,\"Not filled\",\"Filled\")&\"</text>",
              "    <text class='supportText' x='50%' y='\" &_yStartPosition*0.825&\"'>\"&IF(_value>=_total,\"Over: \", \"Missing: \")&\"<tspan class='bolden'>\"&ABS(_value-_total)&\"</tspan></text>\"",
              "VAR _result = _svgDeclaration & _svgHeader & _style & _defs & _bar & _texts & _endLine & _svgEnd",
              "RETURN",
              "    _result"
            ],
            "lineageTag": "992f445a-d1de-4684-b6d2-a32ad2e5a7e6"
          }
        ],
        "partitions": [
          {
            "name": "4. Report-Specific SVG Measures",
            "mode": "import",
            "source": {
              "expression": "{1}",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}